### ISSUE TITLE
External player option does not play on external player

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-android#470] opened 2021-07-17 15:47 UTC
**Describe the bug**

Choosing mxplayer pro as external player doesn't result in mx player playing the video.

Go to video player in settings and set external player one of the external ones.
**Expected behavior**

If vlc or mx player is chosen, it should play with the chosen player.
**Logs**
I will try to get logs from Android studio

**Screenshots**

**System (please complete the following information):**

Sony xz premium, android 9.0, app is latest version from play store. vlc, mpv and mx player pro were tried with.

**Additional context**

    When I build from repository it works, the version from google play doesn't work.

**Comment by CarlosOlivo** [comment] 2021-07-20 05:20
Duplicate of #453 

It is already fixed in the repository, it will be fixed in the next release.

**Closed** 2022-01-24 17:23 UTC
Labels: bug, duplicate
