### ISSUE TITLE
"Start Now" for playing next episode overlaps rewind button

### ISSUE THREAD

**Issue by jcdick1** [jellyfin/jellyfin-android#41] opened 2020-08-23 17:45 UTC
I have an android tablet - B&N 10" Nook - that I use with the JF client.  At the end of any TV episode that has another following, the "Start Now" button comes up at the bottom left.  However, the particular position overlays the rewind button just below the progress bar.  When I press it, instead of starting the next episode, it just rewinds the currently playing episode by 30 seconds.  Is there a way to make the overlay buttons the absolute input for the entire space they occupy?

**Comment by Maxr1998** [comment] 2020-08-23 18:01
I suppose you're using the web player, and the old app from Google Play?

**Comment by JulioNahum** [comment] 2020-08-23 19:41
Now with the new application for Android, they are implementing the Exoplayer player, and perhaps later that error that the old application's web player has will be solved.

**Comment by jcdick1** [comment] 2020-08-23 21:15
This is with whatever version is currently in the Google store.  Is this issue fixed in whatever version will be coming to the store?  If so, then I guess it can be closed.

**Comment by JulioNahum** [comment] 2020-08-23 21:22
It is better to close this error so that you can work calmly in the new jellyfin android application. These errors are from the old version of the store. Hopefully the 3 revision of the new android app will come out soon :)

**Comment by nielsvanvelzen** [comment] 2020-08-24 06:33
Closing since the issue is about the old app. If the issue persists after we release our next version please re-open or submit a new issue, thanks!

**Closed by nielsvanvelzen** 2020-08-24 06:33 UTC
Labels: bug
