### ISSUE TITLE
Active devices info blends in with the background in light mode

### ISSUE THREAD

**Issue by Sync271** [jellyfin/jellyfin-android#617] opened 2022-02-03 19:52 UTC
### Describe the bug

# Initially posted on [jellyfin-web](https://github.com/jellyfin/jellyfin-web) [#3370](https://github.com/jellyfin/jellyfin-web/issues/3370) by [@datsoy](https://github.com/datsoy)
## Checked and Verified by me before posting here
![WhatsApp Image 2022-02-04 at 1 13 25 AM](https://user-images.githubusercontent.com/67158080/152417145-ac3dc8ea-c5d1-40cc-a136-dd0257368e87.jpeg)

### Logs

```shell
None
```

### Application version

2.4.2

### Where did you install the app from?

Google Play

### Device information

Oneplus 6T

### Android version

Android 11

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment] 2022-02-03 20:13
This is an issue with jellyfin-web. Closing as duplicate of jellyfin/jellyfin-web#3370.

**Closed by nielsvanvelzen** 2022-02-03 20:13 UTC
Labels: bug

**Comment by Sync271** [comment] 2022-02-03 20:20
Hey @nielsvanvelzen,
Sorry to bother you but I faced this issue on the android app, is there anything I'm missing here?
On the web it works fine, I checked it multiple times already before posting this issue.
I wanted to contribute to the web project and then realised this was an issue on android.

**Comment by nielsvanvelzen** [comment] 2022-02-03 20:31
The issue occurs in the webui, that's why the issue should be in jellyfin-web.
The Android app is just a webview embedding webui.
