### ISSUE TITLE
Won't play .ogg streams

### ISSUE THREAD

**Issue by Strit** [jellyfin/jellyfin-android#83] opened 2019-02-11 07:23 UTC
Hi there. 
As asked on the jellyfin-app-dev channel on Matrix, I now open this issue.

The Jellyfin Android app (both old one and the new beta4) does not play .ogg audio files.
If I select an .ogg file to  be played I get an error saying:
```
Playback Error
No compatible streams are currently available. Please try again later or contact your system administrator for details.
 [Got it button]
```
It plays .flac's just fine. I don't have any .mp3 or other formats to try with. But most of my music collection is in .ogg.
Playing oggs work fine in the old Emby app though.

This is what happens in the log on the server:
```
[2019-02-11 07:19:33.880 +00:00] [INF] User policy for "Dan". EnableAudioPlaybackTranscoding: True
[2019-02-11 07:19:33.883 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/Musik/Zen In Noise/Stop The Fire/01 - Stop The Fire.ogg"
[2019-02-11 07:19:33.886 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/Musik/Zen In Noise/Stop The Fire/01 - Stop The Fire.ogg"
[2019-02-11 07:19:33.888 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/Musik/Zen In Noise/Stop The Fire/01 - Stop The Fire.ogg"
```

**Comment by Strit** [comment] 2019-02-21 07:13
Just tested with Android app beta5. Still same issue.

**Comment by dkanada** [comment] 2019-02-21 09:54
Just checked the relevant [file](https://github.com/jellyfin/jellyfin-android/blob/master/src/cordova/apphost.js#L34), both ogv and ogm are included but not the ogg extension. We need to look up WebView support for the different ogg types and update that line based on what is supported.

**Comment by Strit** [comment] 2019-03-05 13:06
Beta6 broke flac playback too. The app just hard crashes.
Going back to Beta5 brings back flac playback.

**Comment by dkanada** [comment] 2019-03-05 13:30
That one is likely related to #97 which is suposedly an upstream issue. I haven't been able to look into it yet.

**Comment by dkanada** [comment] 2019-04-08 02:44
Could you post a `mediainfo` report for one of the files? I didn't see anything glaringly obvious so this will require more debugging.

**Comment by Strit** [comment] 2019-04-08 11:20
Sure, here it is, without the Picture meta block:
```
General
Complete name                            : 01 - Stop The Fire.ogg
Format                                   : Ogg
File size                                : 3.58 MiB
Duration                                 : 4 min 11 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 119 kb/s
Album                                    : Stop The Fire (single)
Track name                               : Stop The Fire
Performer                                : Zen In Noise
METADATA_BLOCK_PICTURE                   : (lots of characters....)

Audio
ID                                       : 1995861508 (0x76F66E04)
Format                                   : Vorbis
Format settings, Floor                   : 1
Duration                                 : 4 min 11 s
Bit rate mode                            : Variable
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Compression mode                         : Lossy
Stream size                              : 3.84 MiB
Writing library                          : libVorbis (Now 100% fewer shells) (20180316 (Now 100% fewer shells))
```

**Comment by tareefdev** [comment] 2019-04-20 15:51
I have the same problem here but with mp3 files
Jellyfin server works on Arch Linux 64bit, there is no problem with playing mp3 files using web interface.
But on android (beta9, Android 9), the app could not play mp3 files and shows me the following error:
`Playback Error: No Compatible Stream`
On the server log, there are the following errors:
`[2019-04-20 18:12:22.999 +03:00] [INF] User policy for "tareef". EnableAudioPlaybackTranscoding: True
[2019-04-20 18:12:22.999 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.000 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.001 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.268 +03:00] [INF] User policy for "tareef". EnableAudioPlaybackTranscoding: True
[2019-04-20 18:12:23.269 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.269 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.269 +03:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/mnt/myFiles/Music/Simge/Ba-Dertte-by-Simge--Anghami.mp3"
[2019-04-20 18:12:23.479 +03:00] [INF] Playback stopped reported by app "Jellyfin Mobile" "20854" playing "Ba-Dertte-by-Simge--Anghami". Stopped at "0" ms`

**Comment by bd4** [comment] 2019-05-13 16:31
I have an ubuntu server (jellyfin 10.3.2), client is beta9 on Android 9 (moto x4), mp3 works for me, but Ogg is failing with the following log:
```
[2019-05-13 11:29:32.886 -05:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/extra/bda/music/bandcamp/DJ_Krush/Butterfly_Effect/01 Probability.ogg"
```

**Comment by geekboy01** [comment] 2019-12-15 01:56
I'm having the same issue with .ogg (vorbis) files, If I rename them to .opus (no other change but file rename) they work just fine. So doesn't appear to be a codec issue, only a mimetype issue.

**Comment by geekboy01** [comment] 2019-12-15 15:06
I was having the same issue just changing the file extension from ogg to opus allowed the files to play. While hunting this down I found that minor modifications to the various browserdeviceprofile.js lines 119-121 (if block) if they are commented out the ogg files work just fine. I don't know how to do a pull request for this and was hoping someone could verify and add this to the next release.

            // chrome says probably, but seeing failures
            if (browser.chrome) {
                return false;
            }

**Comment by bd4** [comment] 2019-12-16 20:07
@geekboy01 I just checked and opus works for me too. It looks like the node_modules and www instanses of `browserdeviceprofile.js` come from `jellyfin-web`: https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/browserdeviceprofile.js . They don't exist in the android git repo, and only appear once `npm install` is run. The `npx cordova prepare` command appears to copy the file from the www dir to the platform directory (I verified that it kept my change of commenting out the special case for chrome not supporting ogg). Perhaps we should submit a PR against `jellyfin-web` with the change, if chrome in general really supports it? It's also interesting (surprising?) that the android player is identified as chrome and gets this special case. Or maybe there is some way to have npm or some other build process patch the file or provide it's own version to override?

**Comment by bd4** [comment] 2019-12-16 20:22
FWIW, if I comment out the lines disabling ogg for chrome in jellyfin-web `browserdeviceprofile.js` on my server, I can verify in the log that it no longer transcodes and it plays fine in google chrome 78.0.3904.108. However the transcoding also works, so I'm not sure why that is _not_ working with the andorid client.

**Comment by bd4** [comment] 2019-12-17 15:55
@geekboy01 I confirmed that your fix for playing ogg files works for me as well. I opened an issue in jellyfin-web: https://github.com/jellyfin/jellyfin-web/issues/638. If it makes sense to make the change in jellyfin-web, jellfyin-android can just use the new version and it will be fixed. Otherwise we can come up with a way to hack around it, maybe monkey-patch jellyfin-web after it is pulled in by npm install.

**Comment by geekboy01** [comment] 2019-12-18 20:25
@bd4 Awesome thanks.  Not being a dev myself wasn't sure how to approach what I came across.

**Comment by JustAMan** [comment] 2020-01-10 15:17
cc @dkanada @thornbill

**Comment by dkanada** [comment] 2020-01-10 16:19
[#683](https://github.com/jellyfin/jellyfin-web/pull/683)

**Comment by dkanada** [comment] 2020-01-21 06:54
Should be working in the next release, please comment here if you guys are still having issues then.

**Closed by dkanada** 2020-01-21 06:54 UTC
Labels: bug
