### ISSUE TITLE
There is grey bar where camera cutout is

### ISSUE THREAD

**Issue by Tomik167** [jellyfin/jellyfin-android#295] opened 2021-02-05 09:09 UTC
It's just a little UI bug that is quite annoying esspecialy in night time, where on amoled display it's really noticableon the left side.
Phone is Galaxy s10e
It would be better to make app fullscreen like on Netflix where the cutout overlays video.
![Screenshot_20210205-093944_Jellyfin](https://user-images.githubusercontent.com/45904017/107013002-159a7280-679a-11eb-87f3-fe869ca2f31e.png)

**Comment by Maxr1998** [comment] 2021-02-05 09:52
Duplicate of #255 and already fixed in #272.
If using web player (and not the native player) also see my comment in #289.

**Closed** 2021-02-05 09:53 UTC
Labels: bug, duplicate
