### ISSUE TITLE
The second startup of the jellyfin app on a vivo/iqoo phone is abnormal, and the application data must be cleared before it can be used

### ISSUE THREAD

**Issue by RisE-H** [jellyfin/jellyfin-android#1398] opened 2024-05-26 08:56 UTC
### Describe the bug

1. Install the jellyfin app
2. Login account
3. Return to Android desktop
4. Restart the app
![Screenshot_20240526_164939](https://github.com/jellyfin/jellyfin-android/assets/65761919/7d9753a7-c2df-41ff-a809-830100ebae27)
5. Clearing application data and restarting app ,it works fine.

### Logs

```shell
no logs
```

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Vivo iqoo neo9

### Android version

Android 14，OriainOS4

### Jellyfin server version

10.9.2

### Which video player implementations does this bug apply to?

- [X] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment] 2024-05-26 08:58
Closing as duplicate of https://github.com/jellyfin/jellyfin-android/issues/1382. This is caused by an issue in jellyfin-web that is fixed in 10.9.3.

**Closed by nielsvanvelzen** 2024-05-26 08:58 UTC
Labels: bug

**Comment by RisE-H** [comment] 2024-05-26 09:27
> Closing as duplicate of #1382. This is caused by an issue in jellyfin-web that is fixed in 10.9.3.

I tried using version 10.10.0 in the unstable branch, but it seems to have not been fixed, and this issue still exists
