### ISSUE TITLE
Unable to connnect to the server in HTTPS mode with self-signed certificate

### ISSUE THREAD

**Issue by scienmind** [jellyfin/jellyfin-android#425] opened 2021-06-09 07:24 UTC
**Describe the bug**

**To Reproduce**

1. Configure the server to: enforce HTTPS, use a self-signed certificate, use custom private and public ports and set a base URL (configure port forwarding accordingly)
2. Try to connect to the server using the official android app by entering the server address (e.g `https://my_server.com:12345/base-url`)
3. Press "connect" 
Result: "Unable to reach server" message displayed

4. Enter the exact same address into the web browser, on the same mobile device
Result: The "Sign In" page appears, I can sign in and use the server, unlike via the mobile app.

**Expected behavior**
The Android app is able to connect to the server just as the web browser can

**System (please complete the following information):**
 - App version: 2.2.3-beta.3
 - Android version: Android 10
 - Jellyfin server version: 10.7.5

**Additional context**
I was able to connect to the server using the Android app in HTTP mode using the default ports

**Comment by scienmind** [comment] 2021-06-10 08:55
Update - after some more testing, it seems like the use of a self-signed certificate is the issue.

Are there any plans to add proper support for that?

**Comment by scienmind** [comment] 2021-06-10 08:56
Related/duplicates: https://github.com/jellyfin/jellyfin-android/issues/301

**Comment by scienmind** [comment] 2021-09-13 08:55
Still happens in 2.3.3

**Comment by Maxr1998** [comment] 2021-09-13 09:21
Forgot to ask, did you install the certificate in the Android settings? That might help, since the app should just use the system certificate store.

**Comment by scienmind** [comment] 2021-09-15 04:14
I did, in v2.2.3, but it did not help.

**Comment by scienmind** [comment] 2022-01-24 10:10
As of the current version - v.2.4.2 the issue is still present

**Comment by KileXt** [comment] 2022-01-24 16:46
I can confirm this behavior. The same issue also arise in the IOS version btw. 

I created a root certificate that my device trust and signed the jellyfin cert with it. Now the app does connect. Same on ios. 

The user should be prompted to whether or they want to trust the server cert when self-signed. This doesn't look like an android limitation as for instance the Nextcloud client work with self-signed cert. 

KileXt

**Comment by nodiscc** [comment] 2022-01-24 18:39
I can confirm that [adding the `CA:TRUE` basicConstraint](https://github.com/nodiscc/xsrv/commit/ce79c7506fb2a48244b47f2bc3a21e92d57110a2#diff-db9b2e41e2b690aad3626197acc356927939e868cd378d1aba84abf016099c16) to my self-signed certificates, and re-importing them to the android trust store fixes the problem for me.

**Comment by Maxr1998** [comment] 2022-01-28 12:44
Since it seems to work with the correct configuration, I'm closing this issue.

**Closed by Maxr1998** 2022-01-28 12:44 UTC
Labels: question

**Comment by leb4r** [comment] 2022-03-05 18:17
> Implementing a prompt makes it too easy for users to accept unsafe or hijacked connections and is also not really supported by our API client library. With the correct certificate, installing it in the system should be enough to make it work. For more information, refer to [this answer on StackOverflow](https://stackoverflow.com/a/47212691/2475176).

This statement leaves a sour taste in my mouth... this just pushes people to generate a single certificate and rarely rotate it b/c they need to update all of their devices with the CA or just use insecure connections.

I generate new self-signed certificates every time I make an update to the apps deployed on my LAN, and this is literally the only app that I am having issues with. 

This makes something so simple, unnecessarily harder. I appreciate the thought, but I don't really care, and the possibility of someone hijacking my LAN connection is fairly small, and if they do, my jellyfin connections are probably the least of my worries. This is multimedia we are talking about here, not PII, so what are we actually trying to secure here? 

If there is really a concern of some random user's certificate being hi-jacked, why aren't there pop-ups or disclaimers saying that?  I have to dig to find that it's just the preference of the developers that probably don't have the same problems as the random users they are advocating for. 

Why can't this be something that's enforced when the server is public-facing, where it's a lot easier to generate trusted certificates, and I don't need to update my certificate store every time. Or better yet, why not just let the user make the risk-based decision on their own and perform measures (consistent and frequent certificate rotations) to secure their deployments without needing the devs approval. 

This is literally the only app on my LAN that this is a problem for, so I don't really understand what being accomplished here other than making things harder and potentially less-secure for single-user/LAN-only installations. 

Love the work you all are doing, but don't like the response to this issue. :heart:

**Comment by pmsobrado** [comment] 2022-10-04 09:49
I created the self signed certificate as instructed but my app still won't connect. I'm running Jellyfin from a Docker but it shouldn't make a difference, right?
