### ISSUE TITLE
Unsupported server version

### ISSUE THREAD

**Issue by Teashrock** [jellyfin/jellyfin-android#388] opened 2021-05-14 04:39 UTC
**Describe the bug**
The Android app refuses to connect to server due to "The server uses an unsupported version. Upgrad to the latest version available at jellyfin.org", though I downloaded the latest Windows release version of the server from GitHub and from Google Play (both don't work).

**To Reproduce**
1. Go to 'https://jellyfin.org/downloads/'
2. Click on 'Download' of Windows Stable
3. Download
4. Install
5. Run Console server version
6. Download app from Google Play or apk from GitHub
7. Install it.
8. Run.
9. Try connecting to the server with an IP-address or 'Choose server' button.
10. Get the message 'The server uses an unsupported version. Upgrade to the latest version available at jellyfin.org'

**Expected behavior**
The server is 10.7.5, the app is 2.3.0-beta1. It says 'this update only supports Jellyfin servers on version 10.7.0 and above', but it's a lie, because it does not work, demanding for some non-existing server version

**Logs**
Android app log: https://pastebin.com/LH5Z3shU
Jellyfin Server log: https://pastebin.com/BwH1YSQg

**Screenshots**
![image](https://i.imgur.com/DUGI7Tq.jpg)

**System (please complete the following information):**
 - App version: 2.3.0-beta1
 - Android version: Android 8.0
 - Device manufacturer and model: Huawei MediaPad T5
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: Neither

**Comment by Maxr1998** [comment] 2021-05-14 07:03
Duplicate of #366. The error message is incorrect, there's likely another (network related) issue that prevents connecting.
It was already fixed and will be rolled out in the next version.

**Closed** 2021-05-14 07:04 UTC
Labels: bug, duplicate
