### ISSUE TITLE
Select server shows null and when selecting it crashes

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-android#152] opened 2020-09-29 12:52 UTC
**Describe the bug**

The app closes when selecting the null values shown by the "Select server" button

**To Reproduce**

1. Press 'Select server'
2. It will show 'null'
3. Press 'null' and the application will close

**Expected behavior**

It should show a list of servers

**Screenshots**
![Screenshot_2020-09-29-14-42-18-748_org jellyfin mobile](https://user-images.githubusercontent.com/6619414/94559977-4efa2900-0262-11eb-89de-ec9fc327a922.jpg)

**System (please complete the following information):**
 - App version: 2.0.0-rc.6
 - Android version: Android 10 (MIUI 11.0.9.0)
 - Device manufacturer and model: Pocophone F1
 - Jellyfin server version: 10.5.4

**Comment by nielsvanvelzen** [comment] 2020-09-29 12:54
Duplicate of #147 (and already fixed in the next RC!)

**Closed by nielsvanvelzen** 2020-09-29 12:54 UTC
Labels: bug
