### ISSUE TITLE
Terrible glitches in the UI

### ISSUE THREAD

**Issue by awsms** [jellyfin/jellyfin-android#144] opened 2020-09-27 22:54 UTC
**Describe the bug**
glitches in the whole UI, text and images are messed up. submenus become impossible to use.

**To Reproduce**
just by browsing the menus

**Screenshots**
https://share.riseup.net/#Uui3A3MZz8Y9mVWkU4lAOw
https://share.riseup.net/#8YHprJ1jEGgLM82R6GnApA

**System (please complete the following information):**
 - App version: 2.0.0-rc.5
 - Android version: LineageOS 17 / Android 10
 - Device manufacturer and model: Samsung Galaxy S9+
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment] 2020-09-28 06:54
Does this only happen in the Jellyfin app? Looks like a corrupt video driver to me 😅

**Comment by awsms** [comment] 2020-09-28 17:21
> Does this only happen in the Jellyfin app? Looks like a corrupt video driver to me

lol you're right, but it only happens on jellyfin. i wouldn't have opened an issue otherwise :p

**Comment by Maxr1998** [comment] 2020-09-28 18:35
What WebView implementation are you using? This is a weird issue, have never seen anything like that.

**Comment by johnygum** [comment] 2020-09-30 19:11
I had the same problem (on LOS 17.1, Samsung s10). Disabling "Live Display" fixed it for me.

**Comment by Maxr1998** [comment] 2020-12-13 16:47
@awsms can you check if disabling Live Display also works for you?

**Comment by chrstfer** [comment] 2021-03-03 03:57
Is this still an active issue? The screenshots are gone, so if it is still a problem it would be great if someone could post some more.

**Comment by Maxr1998** [comment] 2021-05-24 22:46
I think this was after all a ROM issue caused by (seemingly) the Live Display feature in LineageOS. Thus closing as invalid.

**Closed** 2021-05-24 22:46 UTC
Labels: bug, invalid
