### ISSUE TITLE
Jittery music playback when screen turns off

### ISSUE THREAD

**Issue by y2kboy23** [jellyfin/jellyfin-android#409] opened 2021-05-25 21:23 UTC
**Describe the bug**
Music playback becomes jittery when the screen turns off or if the app goes to the background.  This issue is not present with using the web-based interface through the Android web browser.

**To Reproduce**
1. Play a song from the Music Library
2. Turn the screen off and playback will become jittery

**Expected behavior**
Playback should continue as if the app were in the foreground

**System**
 - App version: 2.2.3 along with the latest 2.3.0 betas
 - Android version: Android 11
 - Device manufacturer and model: Pixel 3a
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: ExoPlayer

**Comment by Maxr1998** [comment] 2021-05-25 23:43
Duplicate of #39, please see the information there.

**Closed** 2021-05-25 23:43 UTC
Labels: bug, duplicate
