### ISSUE TITLE
False WebViews are not supported by this device message

### ISSUE THREAD

**Issue by T-bond** [jellyfin/jellyfin-android#386] opened 2021-05-12 23:58 UTC
**Describe the bug**

The app says that my device does not support webviews, which is false.
**To Reproduce**

Use Jellyfin (2.3.0-beta1) from FDroid.
Disable Google Play store.
Uodate system webview from other sources (like Apkmirror or Aurora store)
See that Jellyfin refused to start.
![SmartSelect_20210513-015133_Jellyfin](https://user-images.githubusercontent.com/3778556/118058313-39b7b200-b38e-11eb-9fdd-ab6cf83080b6.jpg)

**Expected behavior**

Jellyfin works correctly, as it did with the previous version with older webview, or it should work with never webview at least.
**Logs**

**Screenshots**

![SmartSelect_20210513-015727_Settings](https://user-images.githubusercontent.com/3778556/118058498-987d2b80-b38e-11eb-9f1c-383c53444302.jpg)

**System (please complete the following information):**
 - App version: 2.3.0-beta1
 - Android version: Android 11
 - Device manufacturer and model: Samsung Galaxy S20
 - Jellyfin server version: 10.7.5

**Additional context**

**Comment by nielsvanvelzen** [comment] 2021-05-13 06:40
Duplicate of #383 (slightly different description but same underlying issue).

**Closed by nielsvanvelzen** 2021-05-13 06:40 UTC
Labels: bug

**Comment by CarlosOlivo** [comment] 2021-05-13 17:25
> Duplicate of #383 (slightly different description but same underlying issue).

I'm not sure if it's the same problem, #383 is for outdated versions

https://github.com/jellyfin/jellyfin-android/blob/b092b77236585f5f9edfab414036ebd2de0bc8bb/app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt#L41-L42

But #386 is to verify the existence of WebView support, and I feel that this try catch block is too generic. 

https://github.com/jellyfin/jellyfin-android/blob/b092b77236585f5f9edfab414036ebd2de0bc8bb/app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt#L28-L39

A logcat would be appreciated.
