### ISSUE TITLE
Support ASS subtitles for external player(VLC, MX) or itself 

### ISSUE THREAD

**Issue by wiketor** [jellyfin/jellyfin-android#725] opened 2022-07-01 09:34 UTC
When using external player, it can auto download subtitles, users do not need to download subtitles manually in advance. Also, the ExoPlayer does not support ASS subtitles either.

**Comment by Nalsai** [comment] 2022-10-03 17:40
With mpv all subtitles work perfectly. 
VLC works fine with embedded subtitles, but not with external ones. This has been an issue for 6 years <https://code.videolan.org/videolan/vlc-android/-/issues/1903> and no one has adressed it. It's not jellyfin's fault. 
MX Player is a bit weird: it doesn't show subtitles when using HW decoding. If you switch to SW or HW+ it loads the subtitles (both embedded and external) and they will continue to work, even if you switch back to HW. This might be addressable by adding some MX Player specific code, but it should really just be fixed by the developers of MX Player.

ExoPlayer is slowly adding support for ASS subtitles (<https://github.com/google/ExoPlayer/issues/8435>) - in the next update of jellyfin-android there will be a checkbox to enable ASS support in ExoPlayer even though it is incomplete and only shows basic text.

**Comment by Maxr1998** [comment] 2023-08-30 10:03
<span>#</span>1 should be fixed or is a duplicate of #252, <span>#</span>2 is a duplicate of #587.

**Closed** 2023-08-30 10:03 UTC
Labels: duplicate, enhancement
