### ISSUE TITLE
Jellyfin Crashes when using vlc as the Default player 

### ISSUE THREAD

**Issue by StevMaHo** [jellyfin/jellyfin-android#1075] opened 2023-05-21 22:08 UTC
### Describe the bug

1. Set playback to externel Player
2. Set IT to use vlc ( Version 3.5.4)
3. Play Video
4. See crash

Only Happens with my Mi Pad, on my Smartphone (Xiaomi Mi Mix 2) it works. After downgradeing to vlc 3.4.0 it works again on my Mi pad
![Screenshot_2023-05-21-23-57-47-109_com miui bugreport](https://github.com/jellyfin/jellyfin-android/assets/105807526/3e306896-16f0-4a99-bd72-d03fe5110932)

### Logs

```shell
Bugreport from Android See Picture
```

### Application version

2.5.2

### Where did you install the app from?

Google Play

### Device information

Xiaomi Mi Pad 5

### Android version

Android 13

### Jellyfin server version

1.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by Jpkribs** [comment] 2023-05-22 00:34
It looks like you're experiencing this issue:

https://github.com/jellyfin/jellyfin-android/issues/912

**Comment by nielsvanvelzen** [comment] 2023-05-22 06:23
Closing as duplicate of #912

**Closed by nielsvanvelzen** 2023-05-22 06:23 UTC
Labels: bug
