### ISSUE TITLE
The Android app gets stuck at login after Jellyfin v10.9.0.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin-android#1382] opened 2024-05-14 03:04 UTC
### Describe the bug

Ever since v10.9.0, after a successful login into the app, I can't reopen the Jellyfin Android app on my local network. If I do, I'm greeted with this screen:
![pic1](https://github.com/jellyfin/jellyfin-android/assets/80718617/2902778f-2faa-4021-9708-0eb76a15686d)
The screen doesn't say it can't find the server, but that the connection can't be established. If I tap on the "Connect" button, it just spams my logs with "Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" request". I pasted a snippet of my server logs of when this happens in the log section here. The only way to fix this is to clear out the cache and data stored for the app, and this only works once. I have to keep clearing out the data if I close the app.

I'm running the Jellyfin server as a custom app on a Truenas Scale system. I port forwarded the 8096 port to 9001.
Strangely enough, I'm able to enter and use the Android app if I disconnect from my local network and start my Tailscale VPN.

I've tried the community app of Jellyfin that Truenas offers to use Host Networking to see if this solved my issue.
Enabling Host Networking does solve my issue of local network access, but it now breaks my Tailscale access for when I'm away from my local network. When this happens, I get greeted with a loading circle that takes a while to bring me to a server select screen. The only way to get the app to work again is to delete the server at this screen, close the app, and reopen it. For some reason, this issue doesn't generate any logs. And just in case, I also ran into the same issue on a Synology nas while running Jellyfin v10.9.1 from a Docker container.

### Logs

```shell
[INF] [26] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "max" has succeeded.
[INF] [26] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "max": 1/0
[INF] [26] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user <redacted>
[INF] [16] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" request
[WRN] [28] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.190" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" closed
[INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" request
[INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" request
[INF] [26] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.190" request
```

### Application version

2.6.1

### Where did you install the app from?

Google Play

### Device information

Samsung Galaxy Note 9

### Android version

Android 10 (w/ Samsung's One UI v2.5)

### Jellyfin server version

10.9.1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by KimPig** [comment] 2024-05-14 04:41
same here. Can't reconnect via reverse proxy.

**Comment by EHRETic** [comment] 2024-05-14 16:48
Hi there,

Same for me, stuck on the JF logo and no way to get it past it ;-)

**Comment by KimPig** [comment] 2024-05-15 04:56
> semi able to replicate- updated to 10.9.1, signed out of active sessions on pixel 6 pro and experienced the same issues with 2.6.1 and debug built from the latest master branch. signing out all devices on the server dashboard / clearing cache / data seems to have fixed the issue on both the debug and 2.6.1 release versions. accessing the server remotely through tailscale also works after clearing data.
> 
> tested on physical pixel 6 pro android 14 (play store release / current master) and emulator pixel 8 pro android 14 (current master). i have an old samsung somewhere i can test on, if i can find it.

That's strange. I've deleted all devices from the server dashboard after updating to 10.9.0 and reinstalled the app on my phone, but I'm still having the same problem.

**Comment by taitsmith** [comment] 2024-05-17 13:28
> I have the same Issue, but only on one of my devices.
> 
> Both run Android 8.1 Both run Jellyfin Android 2.6.1 Server Version 10.9.1

interesting. can you post a bit of the server logs from when you (attempt) to connect with both devices? i’m still unable to reliably reproduce this with the 2.6.1 release, but building from the current master branch doesn’t seem to have any issues. 

i do have a separate / potentially related issue on both android and ios but need to look into it more.

**Comment by maru801** [comment] 2024-05-17 14:03
I think being able to reliably reproduce this issue depends on what and how the Jellyfin server is installed.

I have a Truenas Scale NAS & a Synology NAS.

Using the Jellyfin server on my Truenas Scale system, I get this Android error while on my local network. Using a VPN to use an external network makes everything work fine though on it. If I enable host mode network, local network works and the Android app doesn't run into this issue, but then fails to connect at times while on the VPN.

On the Synology with Jellyfin running in a Docker container, local network also works fine but my VPN stops working.

**Comment by taitsmith** [comment] 2024-05-17 17:38
> I guess server version 10.9.0+ has introduced some bugs in Networking.

i was leaning towards this as well since i’ve had issues with android and ios (but not android tv or web). the most common issue on 2.6.1 on android results from the webview throwing a 404 and displaying an empty screen, but i havent found anything specific to the servers not showing up.

**Comment by DisloyalSnow911** [comment] 2024-05-17 18:36
I have the same problem, just like the author.

**Comment by maru801** [comment] 2024-05-17 23:07
I would also like to point out that if I wait a few hours at random, the app usually enters my server just fine, then breaks if I close it afterwards.

**Comment by rusticrooster** [comment] 2024-05-18 03:18
I have the same problem. This is happening on my LAN and WAN for two android phones, but not my android TV. My devices are Android Galaxy S23. The web browser works fine. For the server configuration I am not using a reverse proxy or HTTPS. I am using Tailscale VPN. Let me know if you'd like more details.

**Comment by svenlindekugel** [comment] 2024-05-18 09:14
this could be related to:

[https://github.com/jellyfin/jellyfin/issues/11598](url) => Fix stored credentials not updating on logout jellyfin/jellyfin-web#5500

**Comment by maru801** [comment] 2024-05-18 16:15
> this could be related to:
> 
> [https://github.com/jellyfin/jellyfin/issues/11598](url) => Fix stored credentials not updating on logout [jellyfin/jellyfin-web#5500](https://github.com/jellyfin/jellyfin-web/pull/5500)
> 
> unfortunatly this fix is not included in yesterday released 10.9.2

I'm confused. Isn't this fix mentioned as being included in the release notes on the [jellyfin-web v10.9.2 release](https://github.com/jellyfin/jellyfin-web/releases/tag/v10.9.2)?

From the release notes on that page:
> - Fix stored credentials not updating on logout [PR [#5500](https://github.com/jellyfin/jellyfin-web/pull/5500)], by @thornbill

**Comment by thornbill** [comment] 2024-05-18 16:35
Yes that PR was included in 10.9.2.

**Comment by taitsmith** [comment] 2024-05-18 17:17
> Yes that PR was included in 10.9.2.

seems to have resolved all relevant issues as i'm now unable to reproduce these on android or ios.

**Comment by rusticrooster** [comment] 2024-05-18 17:20
I can confirm the issue persists following the 10.9.2 update.

**Comment by rusticrooster** [comment] 2024-05-18 17:31
Tested this out on an iPad 6th generation OS version 17.4.1 - no issues.

**Comment by taitsmith** [comment] 2024-05-18 17:36
@rusticrooster have you tried clearing storage / cache on your devices and starting fresh in that way? if you could post a bit of the server logs also that'd help narrow things down.

is your issue connecting to the server like the original screenshot? or are you able to log in successfully and then have errors on subsequent logins.

**Comment by maru801** [comment] 2024-05-18 17:55
One thing I noticed is that if you log into multiple accounts on the Android app, the server's Devices section in the admin dashboard does not create a new instance/device per user logged in.

The way it worked before, each new user that logged into the same device counted as a new separate device in the dashboard. I wonder if this has something to do with this issue.

The Jellyfin Media Player program was updated today, and logging into multiple accounts on that does produce multiple devices on the server. So far, my browser and the Android app just replace the name of the last logged-in user over the single device.

**Comment by rusticrooster** [comment] 2024-05-18 17:59
Is there a clean way to post the logs?

**Comment by Crispychickenlegs** [comment] 2024-05-18 19:06
> I have the same Issue, but only on one of my devices.
> 
> Both run Android 8.1 Both run Jellyfin Android 2.6.1 Server Version 10.9.1
> 
> Behavior of the Problem Device:
> 
> * Fresh reinstall
> * First time connecting to server via local ip: 192.168.1.14:8096
> * Login successful
> * Close app
> * Reopen app
> * Connection to server can't be established.
> * Close app and delete all app data
> * Add Server ip
> * Connecting to server works again until app is closed, than the cycle repeats.

I have exactly this issue also. I can use local IP and external address to access the server exactly once. After that all app data must be deleted for them to work again. This issue only occurs on my phone (Pixel 7), all other devices such as Chromecast or web browser have no issues.

I can't access server logs st this stage but will update with them when I can

**Comment by omelettedufromagee** [comment] 2024-05-19 02:56
Just adding myself to this issue:
- Jellyfin Server 10.9.2
- Cleared all data from Jellyfin Android Client
- Can log once either locally or remotely
- Close Android Client, launch again, got the login page
- Try to login, I get "Connection cannot be established" error message

I cleared all sessions in Jellyfin Server. I'm able to use Findroid without a problem.
![image](https://github.com/jellyfin/jellyfin-android/assets/7980742/061251a1-35c5-48fb-a034-fd5f4590197d)

**Comment by scampower3** [comment] 2024-05-19 08:08
I might have a potential fix here. 

I had the same problem where I can only login once before it fails to connect on LAN. However, I can access the Jellyfin server just fine when I am outside through my nginx reverse proxy. Setting the Bind to local network address to the LAN ip fixes that issue for me.

**Comment by maru801** [comment] 2024-05-19 15:41
> Setting the Bind to local network address to the server's LAN ip ( in this case the docker's 172.17. 0.0/16 ip address) fixes that issue for me.
I get a similar result with enabling host mode. My phone will work on LAN, but now will not work right when I switch to remote with a Tailscale VPN.

**Comment by scampower3** [comment] 2024-05-19 15:48
> > Setting the Bind to local network address to the server's LAN ip ( in this case the docker's 172.17. 0.0/16 ip address) fixes that issue for me.
> 
> I get a similar result with enabling host network mode. My phone will work on LAN, but now will not work right when I switch to remote with a Tailscale VPN. Not using host mode results in the opposite.

Try setting ur docker to be in bridge mode and in Dashboard > Networking and input the Bind to local network address field to be ur docker internal ip (should be in the 172.17. 0.0/16 range)

**Comment by maru801** [comment] 2024-05-19 17:45
Tried that. Didn't help me or I'm doing something wrong. Thanks for the tip though.

To clarify though, when I switch to host network mode, remote connections don't break like the way described when I started this issue. It's more of a "soft-break". What I mean is that if I switch from local to remote with the VPN, it will log-in once on the VPN just fine. Then closing the app and opening it again results in a blue circle spinning for a good minute. After some time, the app will take me to a screen to select a server with my server on the screen. Trying to access my server through that will not work, I have to delete it and reinput my server IP to get access back. So it's not like the issue here where local network just straight up refuses to even do anything.

Also, I got a question about the bind network option. Looking at the logs, I keep seeing this: "Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]"

Isn't the bind address supposed to change to whatever address I inserted in the "Bind to local network address" field in the network settings?

**Comment by daniskarma** [comment] 2024-05-19 22:02
I can confirm this is still an issue with jellyfin server 10.9.2. installed in a docker container and android jellyfin 2.6.1. It started happening just as I updated the jellyfin server to over 10.9.0. Clearing data and cache does work until the app closes, once it need reconnect the connection to the server fails as described by author.

It doesn't seem to happen with other jellyfin client I've have installed, Gelly.

**Comment by taitsmith** [comment] 2024-05-19 22:49
seems like a lot of the remaining issues are related to servers running in docker- anyone still receiving notifications here can confirm or deny this that'd be helpful.

**Comment by rusticrooster** [comment] 2024-05-19 23:12
I am running on (Dragonfish) TrueNAS Scale, using the Jellyfin app made available by Truecharts. I believe the app uses Docker.

**Comment by maru801** [comment] 2024-05-19 23:25
> I am running on (Dragonfish) TrueNAS Scale, using the Jellyfin app made available by Truecharts. I believe the app uses Docker.

Yeah it does in a way. Truenas Scale uses a wrapper to run Docker images within Kubernetes (k3s in this case).

I'm also running my Jellyfin server on Truenas Scale (v24.04.0 - Dragonfish).
The only difference is that I'm running the official Jellyfin image as a custom app and not using the community or Truecharts provided Jellyfin apps. I pulled the image from Jellyfin's github.

If it helps, I'm also running Jellyfin on a Synology NAS using Docker using the same image. The only difference is the opposite happens (local network works, switching to remote breaks things).

**Comment by Crispychickenlegs** [comment] 2024-05-19 23:31
Confirming that server Jellyfin Server is running in docker.
I've just tried again and it is still happening from android app, but only when attempting to connect remotely through Tailscale.

Here are some more logs:

Initial login via remote connection:
```shell
[11:19:45] [INF] [38] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[11:19:45] [INF] [38] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 0/0
[11:19:45] [INF] [38] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 4e944a8b-e80c-4b94-bbc9-44b8eb823205
``` 

After this, closed app without signing out.
Attempt to reconnect using same URL after this results in connection cannot be established and the following entries into the server log:
```shell
[11:19:45] [INF] [44] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:11] [INF] [47] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:19] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:24] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:30] [INF] [46] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:56] [INF] [46] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:20:57] [WRN] [46] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:20:57] [WRN] [50] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:20:57] [INF] [46] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:20:57] [INF] [50] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:20:57] [WRN] [52] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:20:57] [INF] [52] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:20:57] [WRN] [52] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:20:57] [INF] [52] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:20:57] [WRN] [46] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:20:57] [INF] [46] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:21:09] [INF] [52] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
[11:21:10] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
[11:22:35] [INF] [50] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[11:22:47] [INF] [50] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[11:24:10] [WRN] [48] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 100.74.95.46 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[11:24:10] [INF] [48] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 closed
``` 

Any further attempts results in:
```shell
[11:29:54] [INF] [32] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 100.74.95.46 request
```

**Comment by KimPig** [comment] 2024-05-20 01:19
I'm running Jellyfin server on Windows, and I've built a reverse proxy with NPM, but I still can't resolve this error. It works without problem on the web or third-party apps such as Findroid.

**Comment by QingFei7931** [comment] 2024-05-20 14:58
There is an abnormal situation that makes it impossible to log in
Log in and play for about 3 minutes before jumping back to the login screen.
And it prompts that the connection cannot be established.

Application version
2.6.1

Where did you install the app from?
Google Play

Device information
Samsung Galaxy A53 5G

Android version
Android 14 (One UI v6.0)

Jellyfin server version
10.9.2

Which video player implementations does this bug apply to?
Web player (default)


The same device is installed
Jellyfin for Android TV 0.16.10
There is no problem at all if you put it in

The above Traditional Chinese content comes from GOOGLE Translate
Excuse my English skills...

**Comment by nielsvanvelzen** [comment] 2024-05-21 08:00
Closing this issue as it has been fixed in 10.9.3 via jellyfin/jellyfin-web#5566.

**Closed by nielsvanvelzen** 2024-05-21 08:00 UTC
Labels: bug

**Comment by nielsvanvelzen** [comment] 2024-05-21 08:35
Just the server once the release is published, which includes the web interface that caused the issue.

**Comment by maru801** [comment] 2024-05-27 01:48
It fixed the issue on my end. Seems weird that it didn't for you.

**Comment by maru801** [comment] 2024-05-27 06:18
> Version 10.9.3 still has the same issue.

I found out that deleting your devices in the dashboard will break the app (and all other clients) from loading properly. Are you still stuck on the connection page as shown on the image I shared when I created this issue? Or do you at least get past that?

Maybe try clearing out your app data one more time if it's the latter.

**Comment by ierc** [comment] 2024-06-03 02:57
> Sure thing, taitsmith. The issue is produced by:
> 
>     1. clear all app data or fresh install Jellyfin.
> 
>     2. open Jellyfin and access the server, logging in is optional to reproduce as simply accessing the server is enough to trigger it.
> 
>     3. move away from the Jellyfin app in some way, minimize it or switch apps or go to the home screen.
> 
>     4. return to the Jellyfin app and you will see an error just like the image in the original post, you will not be able to access the server again until you delete all app data or reinstall the Jellyfin app.

I'm running into this exact issue. Seems to be happening no matter what Android version I have installed on my phone. Tried the past few from appmirror and nothing works. I even tried versioning back my server with docker with no success.

**Comment by Anexgohan** [comment] 2024-10-07 20:57
adding my 2cent too, having the exact issues described here, android app can connect over mobile network but not on the same wifi that my server is connected through via lan.

**Comment by ZOXSOCKS** [comment] 2024-12-20 00:25
I'm having this problem with my setup too. Able to connect remotely but not on the same wifi network via LAN. 

Hoping for a fix soon.

**Comment by VoiletDragon** [comment] 2024-12-27 15:34
Hi folks, This problem is still kinda present but it's very different, you can log in watch content but after so long it will go to the screenshot in Post 1, tested local and behind Nginx Reverse Proxy but the same issue remains, only seems to happen on Android Jellyfin App on Samsung devices.

I cannot re-produce the problem on Desktop browsers, Desktop Linux app neither are friends and family are having this problems. Android TV Jellyfin App works though. 

Version of Jellyfin 10.9.9 non docker, installed directly from  https://repo.jellyfin.org/ubuntu Repository.

Regards

![Image](https://github.com/user-attachments/assets/18c0d3f4-06f7-4bee-a492-4461cf23dd06)

**Comment by C-seeker2001** [comment] 2025-01-13 21:40
> Hi folks, This problem is still kinda present but it's very different, you can log in watch content but after so long it will go to the screenshot in Post 1, tested local and behind Nginx Reverse Proxy but the same issue remains, only seems to happen on Android Jellyfin App on Samsung devices.
> 
> I cannot re-produce the problem on Desktop browsers, Desktop Linux app neither are friends and family are having this problems. Android TV Jellyfin App works though.
> 
> Version of Jellyfin 10.9.9 non docker, installed directly from https://repo.jellyfin.org/ubuntu Repository.
> 
> Regards
> 
> ![Image](https://github.com/user-attachments/assets/18c0d3f4-06f7-4bee-a492-4461cf23dd06)

Same at my end, can connect using a web browser on all Android devices, but the app doesn't work at all.

Jellyfin version: 10.10.3
Android app: 2.6.2

**Comment by VoiletDragon** [comment] 2025-01-13 21:56
> > Hi folks, This problem is still kinda present but it's very different, you can log in watch content but after so long it will go to the screenshot in Post 1, tested local and behind Nginx Reverse Proxy but the same issue remains, only seems to happen on Android Jellyfin App on Samsung devices.
> > I cannot re-produce the problem on Desktop browsers, Desktop Linux app neither are friends and family are having this problems. Android TV Jellyfin App works though.
> > Version of Jellyfin 10.9.9 non docker, installed directly from https://repo.jellyfin.org/ubuntu Repository.
> > Regards
> > ![Image](https://github.com/user-attachments/assets/18c0d3f4-06f7-4bee-a492-4461cf23dd06)
> 
> Same at my end, can connect using a web browser on all Android devices, but the app doesn't work at all.
> 
> Jellyfin version: 10.10.3 Android app: 2.6.2


I can log in fine, even straight away when I am booted out. What happens when you try and log in using the app?

**Comment by TrustAsia** [comment] 2025-01-24 05:26
I have the same issue on my Poco F2 Pro(MIUI12.5.7/Android11) using android client 2.6.2 and server 10.10.3.
The server installed on my ArchLinux server, directly using the package "extra/jellyfin-server 10.10.3-1", "extra/jellyfin-web 10.10.3-1" and "extra/jellyfin-ffmpeg 1:7.0.2p8-1".
The server is available on my Xiaomi Pad 6 (MIUI14/Android13) and iQOO 12 Pro (OriginOS5/Android15) with same version of client.
BTW, the server is available on browser in my Poco, it's unavailable on the client.

![Image](https://github.com/user-attachments/assets/209030d7-30c7-4414-b069-03e4bd02dd11)

![Image](https://github.com/user-attachments/assets/7b0285b8-089c-417a-bde1-5f6c6e921ceb)

![Image](https://github.com/user-attachments/assets/b2059322-75c0-4cb7-bcbe-7a88ce0378d5)

**Comment by UrbanTechIO** [comment] 2025-02-23 15:03
I add my voice to the rest, This problem still exist,
Accessing the service using web browser is working but the android app gives the same message in the first picture of this post, when is it going to be resolved.
Android device, Samsung S23
SERVER: Raspbery pi 5, running docker
Jellyfin service 10.10.6
Android App: 2.6.2
Cloudflare tunnel remote access

**Comment by ZOXSOCKS** [comment] 2025-03-20 00:03
This problem still exists. Will we see any fixes?

**Comment by dmdymov** [comment] 2025-04-03 20:40
Problem still exists

**Comment by pruthvirathod** [comment] 2025-04-09 00:51
I'd like to report that I'm still facing this issue as well.

**Comment by Pentaphon** [comment] 2025-04-14 19:07
I don't see this issue with Jellyfin 10.10.7 but I also have a very simple home server that uses the default 8096 port. Perhaps this is a result of port forwarding to another port.

**Comment by aygupt1822** [comment] 2025-04-16 11:54
Having the same issue with the latest Android version 2.6.1.

I can connect with my local ip(192.168.0.104:8096) but cannot connect with my domain (jellyfin.domain.com)

**Comment by PKBekons** [comment] 2025-08-14 20:14
Same.
