### ISSUE TITLE
Notch area is grey, and never used

### ISSUE THREAD

**Issue by TheFrenchGhosty** [jellyfin/jellyfin-android#289] opened 2021-01-27 14:18 UTC
**Describe the bug**

One of my user reported a problem with phones that have a notch area: Jellyfin will never use it, even if set to fill, and this notch area will always stays grey.

**To Reproduce**

Open any video on a phone that have a notch.

**Expected behavior**

It's black and can be used.

**Logs**

N/A

**Screenshots**

![s](https://user-images.githubusercontent.com/47571719/106003063-bce81d00-60a9-11eb-997f-cbbbeaabb247.jpg)
![s2](https://user-images.githubusercontent.com/47571719/106003088-c2456780-60a9-11eb-98a2-203b554602e5.jpg)

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: 10
 - Device manufacturer and model: Private, unless you really need to know
 - Jellyfin server version: 10.7.0-rc2 (also a problem on 10.7.0-rc3)
 - The type of video player implementation used: Web

**Additional context**

Problem already reported on the Matrix discussion room, I was told by @ferferga to open an issue here.

This user would to have the notch area used for the video, and I was told that after this is fixed it should work properly when the aspect ratio is set to cover.

**Comment by nielsvanvelzen** [comment] 2021-01-27 14:50
The web player won't use the notch area, try using the native player.

**Comment by ferferga** [comment] 2021-01-27 14:53
@nielsvanvelzen Indeed, please move this to web

**Comment by nielsvanvelzen** [comment] 2021-01-27 14:59
I think the issue belongs to the android repository since this is a side-effect of the webview in the Android app. Although I expect it's not something we can fix.

**Comment by Maxr1998** [comment] 2021-01-27 16:15
Partial duplicate of #255 and already fixed in #272. Extending the web player into the notch area won't be supported since the web player will eventually be removed anyway, use the native player for fullscreen playback if possible.

**Closed** 2021-01-27 16:15 UTC
Labels: bug, duplicate
