### ISSUE TITLE
Distorted Sound when in background

### ISSUE THREAD

**Issue by SweetthD3ViL** [jellyfin/jellyfin-android#407] opened 2021-05-24 21:06 UTC
Hello all,

Using the beta-2 at the moment as the beta-3 is still not available from the playstore. 

Reading various post, I change the battery settings to allow Jellyfin to operate in the background and when the screen is off and had no issue with the none beta version prior. 

However, now I do. But from reading the release note, the beta is now using the exoplayer that is integrated in Android (or am I misunderstanding it?) 

Is there a setting to change on the app or the server? 

Using beta-2 on Android 11 and latest 10.5.7 server.

Many, many thanks for your hard work! 

Thank you and I am looking forward to your reply.

**Comment by Maxr1998** [comment] 2021-05-24 22:35
Duplicate of #39. Will be fixed once we switched to native audio playback.

**Closed** 2021-05-24 22:36 UTC
Labels: bug, duplicate
