### ISSUE TITLE
ExoPlayer cannot select bitrate/quality

### ISSUE THREAD

**Issue by db-one** [jellyfin/jellyfin-android#268] opened 2020-12-12 08:58 UTC
Currently, ExoPlayer cannot select bitrate/quality. I would like to see similar functionality as when watching directly in the web, and selecting the gear> Quality.

**Comment by Maxr1998** [comment] 2021-06-04 08:37
Duplicate of #24.

**Closed** 2021-06-04 08:37 UTC
Labels: duplicate, enhancement, exoplayer
