### ISSUE TITLE
Audio doest not change

### ISSUE THREAD

**Issue by GoatFreezy** [jellyfin/jellyfin-android#339] opened 2020-05-08 15:48 UTC
Hello,
I've deployed jellyfin with docker on my server. 
It works pretty well on web browser but with the android application there is no way to change audio settings. It always use the first one it seems and when changing the app seems to be reloading to get the correct one but it doenst change.
I tried on many diferrents series.

This is the log when i change audio.
```
[16:54:11] [INF] User policy for GoatFreezy. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[16:54:11] [INF] Profile: Unknown Profile, Path: /data/tvshows/kai/Fairy Tail/Saga 1/Fairy Tail Kai - 01 - La Meilleure des Guildes.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[16:54:11] [INF] RemoteClientBitrateLimit: 5000000, RemoteIp: IP_ADDRESS, IsInLocalNetwork: False
[16:54:11] [INF] Profile: Unknown Profile, Path: /data/tvshows/kai/Fairy Tail/Saga 1/Fairy Tail Kai - 01 - La Meilleure des Guildes.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[16:54:11] [INF] RemoteClientBitrateLimit: 5000000, RemoteIp: IP_ADDRESS, IsInLocalNetwork: False
[16:54:11] [INF] Profile: Unknown Profile, Path: /data/tvshows/kai/Fairy Tail/Saga 1/Fairy Tail Kai - 01 - La Meilleure des Guildes.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[16:54:12] [ERR] Error processing request: The operation was canceled.
```
Let me know if there is any information i should look for to be able to debug this.

Tanks for your help

**Comment by thornbill** [comment] 2020-08-02 04:20
Seems like this is a duplicate of #328.

**Closed by thornbill** 2020-08-02 04:20 UTC
