### ISSUE TITLE
App crash when connection is lost during playback in native player

### ISSUE THREAD

**Issue by laurinneff** [jellyfin/jellyfin-android#328] opened 2021-03-25 17:29 UTC
**Describe the bug**

When playing a file in the native player, if the connection is lost (for example when moving out of range of a cell tower), the app crashes

**To Reproduce**

1. Play a file using the native player
2. Disconnect from the internet
3. The app crashes

**Expected behavior**

I'd expect the app to show an error message saying that the connection was lost and wait for a connection and continue playing

**Logs**

[logcat.txt](https://github.com/jellyfin/jellyfin-android/files/6206643/logcat.txt)

The crash occurs at line 13066

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 11
 - Device manufacturer and model: OnePlus 7T and Samsung Galaxy Tab S7+
 - Jellyfin server version: 10.7.0
 - The type of video player implementation used: Native player

**Comment by Maxr1998** [comment] 2021-03-25 20:43
As the label already suggests, that bug is caused by the old apiclient. It will be fixed once we migrated to the new one.

**Comment by CarlosOlivo** [comment] 2021-05-19 04:30
Bump, this still happens with with current master (& sdk 1.0.0-beta.4)

```
2021-05-18 18:13:03.331 15144-15144/org.jellyfin.mobile.debug E/RedScreenOfDeath: ══════════ Exception caught by Red Screen Of Death library ═════════
2021-05-18 18:13:03.333 15144-15144/org.jellyfin.mobile.debug E/RedScreenOfDeath: SocketTimeoutException
    io.ktor.network.sockets.SocketTimeoutException: Socket timeout has expired [url=https://demo.jellyfin.org/stable/Sessions/Playing/Stopped, socket_timeout=unknown] ms
        at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:207)
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:77)
        at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
        at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-05-18 18:13:03.333 15144-15144/org.jellyfin.mobile.debug E/RedScreenOfDeath: ════════════════════════════════════════════════════════════════════
```

**Comment by Maxr1998** [comment] 2021-05-19 08:32
@CarlosOlivo that's a different error from the one reported above though, #368 fits a bit more. I'll reopen that one and comment there. This one can also be closed since it only applies to the old apiclient.

**Closed** 2021-05-19 08:32 UTC
Labels: bug, exoplayer, waiting-for-new-sdk
