### ISSUE TITLE
When playing music in the background in the new Jellyfin Android app, the sound is choppy and paused for a few seconds.

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#117] opened 2020-09-11 17:18 UTC
**Describe the bug**
When playing music in the background the sound comes out with micro cuts that are audible and with some "speed" drops in the melody.

**System:**
 - App version: 2.0.0-rc.4]
 - Android version: [Android 9]
 - Device manufacturer and model: [LG K50s]
 - Jellyfin server version: [10.6.4]
 - The type of video player implementation used: [(ExoPlayer)] (Activating the option to play music in the background)

**Comment by nielsvanvelzen** [comment] 2020-09-11 17:53
Duplicate of #39

**Closed by nielsvanvelzen** 2020-09-11 17:53 UTC
Labels: bug, duplicate
