### ISSUE TITLE
the books are not downloaded

### ISSUE THREAD

**Issue by Bandid0** [jellyfin/jellyfin-android#312] opened 2021-02-25 11:52 UTC
**Describe the bug**
Does not download books when pressing the download icon

**Expected behavior**
The book must be downloaded if downloads are authorized in the configuration

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 10
 - Device manufacturer and model: Several
 - Jellyfin server version: all

**Comment by chrstfer** [comment] 2021-03-04 07:25
Have you tried with audiobooks, or only ebooks? 

I am able to download an audiobook from a books library with the same app version (google play release) on android 11.

**Comment by Bandid0** [comment] 2021-03-04 09:15
I have only tried with epub

**Comment by chrstfer** [comment] 2021-03-04 09:20
Could you paste your jellyfin logs while trying to download an epub, and
also while trying to download an audiobook? I want to see what the server
has to say and compare the two events. If you don't have any audiobooks, i
think it should be the same if you must put a song into the books library.

**Comment by Bandid0** [comment] 2021-03-04 09:44
[2021-03-04 10:38:52.699 +01:00] [INF] [1] Main: Jellyfin version: "10.8.0"
[2021-03-04 10:38:52.717 +01:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, H:\Jellyfin2\Data\log]"]
[2021-03-04 10:38:52.721 +01:00] [INF] [1] Main: Arguments: ["H:\Jellyfin2\jellyfin.dll", "--d", "H:\Jellyfin2\Data"]
[2021-03-04 10:38:52.725 +01:00] [INF] [1] Main: Operating system: "Windows"
[2021-03-04 10:38:52.727 +01:00] [INF] [1] Main: Architecture: X64
[2021-03-04 10:38:52.729 +01:00] [INF] [1] Main: 64-Bit Process: True
[2021-03-04 10:38:52.731 +01:00] [INF] [1] Main: User Interactive: True
[2021-03-04 10:38:52.732 +01:00] [INF] [1] Main: Processor count: 12
[2021-03-04 10:38:52.734 +01:00] [INF] [1] Main: Program data path: "H:\Jellyfin2\Data"
[2021-03-04 10:38:52.735 +01:00] [INF] [1] Main: Web resources path: "H:\Jellyfin2\jellyfin-web"
[2021-03-04 10:38:52.737 +01:00] [INF] [1] Main: Application directory: "H:\Jellyfin2\"
[2021-03-04 10:38:52.849 +01:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "H:\Jellyfin2\Data\cache"
[2021-03-04 10:38:52.922 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-03-04 10:38:52.924 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-03-04 10:38:52.926 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-03-04 10:38:52.938 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-03-04 10:38:52.940 +01:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-03-04 10:38:52.993 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2021-03-04 10:38:53.003 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bookshelf, Version=5.2103.312.349, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\Bookshelf_5.2103.312.349\Jellyfin.Plugin.Bookshelf.dll"
[2021-03-04 10:38:53.005 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=10.2103.312.526, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\Open Subtitles_10.2103.312.526\Jellyfin.Plugin.OpenSubtitles.dll"
[2021-03-04 10:38:53.009 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\Open Subtitles_10.2103.312.526\OpenSubtitlesHandler.dll"
[2021-03-04 10:38:53.012 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Tvdb, Version=2.2103.312.702, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\TheTVDB_2.2103.312.702\Jellyfin.Plugin.Tvdb.dll"
[2021-03-04 10:38:53.017 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\TheTVDB_2.2103.312.702\TvDbSharper.dll"
[2021-03-04 10:38:53.021 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TMDbBoxSets, Version=7.2103.312.641, Culture=neutral, PublicKeyToken=null" from "H:\Jellyfin2\Data\plugins\TMDb Box Sets_7.2103.312.641\Jellyfin.Plugin.TMDbBoxSets.dll"
[2021-03-04 10:38:54.854 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bookshelf" "5.2103.312.349"
[2021-03-04 10:38:54.858 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Open Subtitles" "10.2103.312.526"
[2021-03-04 10:38:54.864 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "2.2103.312.702"
[2021-03-04 10:38:54.871 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb Box Sets" "7.2103.312.641"
[2021-03-04 10:38:54.873 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.0.0"
[2021-03-04 10:38:54.875 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.0.0"
[2021-03-04 10:38:54.877 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.0.0"
[2021-03-04 10:38:54.937 +01:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2021-03-04 10:38:55.193 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2021-03-04 10:38:55.207 +01:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extraer imágenes de los capítulos" set to fire at 2021-03-05 02:00:00.000 +01:00, which is 15:21:04.7929484 from now.
[2021-03-04 10:38:55.277 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "4.3.1"
[2021-03-04 10:38:55.341 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2021-03-04 10:38:55.399 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2021-03-04 10:38:55.446 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2021-03-04 10:38:55.450 +01:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: "H:\Jellyfin2\ffmpeg.exe"
[2021-03-04 10:38:55.453 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "66d89407dcd0475e8e77333ec6154363"
[2021-03-04 10:38:55.533 +01:00] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.1.33/24"
[2021-03-04 10:38:55.548 +01:00] [INF] [1] Emby.Dlna.Main.DlnaEntryPoint: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.56.1/24"
[2021-03-04 10:38:55.551 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0895866
[2021-03-04 10:38:55.553 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2021-03-04 10:38:55.660 +01:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory X:\Peliculas
[2021-03-04 10:38:55.660 +01:00] [INF] [5] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory H:\Servidor FTP\Libros
[2021-03-04 10:38:55.660 +01:00] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory W:\Musica
[2021-03-04 10:38:55.661 +01:00] [INF] [1] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Starting NAT discovery
[2021-03-04 10:38:55.727 +01:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1729579
[2021-03-04 10:38:55.729 +01:00] [INF] [1] Main: Startup complete 0:00:03.1715213
[2021-03-04 10:38:58.222 +01:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Actualizar extensiones"
[2021-03-04 10:38:58.224 +01:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2021-03-04 10:38:58.227 +01:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Actualizar extensiones"
[2021-03-04 10:38:59.788 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Actualizar extensiones" Completed after 0 minute(s) and 1 seconds
[2021-03-04 10:38:59.801 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-03-04 10:39:07.678 +01:00] [INF] [15] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "83.38.65.212" request
[2021-03-04 10:40:06.375 +01:00] [WRN] [8] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "83.38.65.212" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2021-03-04 10:40:06.388 +01:00] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "83.38.65.212" closed
[2021-03-04 10:40:18.624 +01:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
[2021-03-04 10:40:18.627 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2021-03-04 10:40:18.629 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EmbyTV"
[2021-03-04 10:40:18.631 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "TMDbBoxSetManager"
[2021-03-04 10:40:18.633 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2021-03-04 10:40:18.634 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryMonitorStartup"
[2021-03-04 10:40:18.637 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "ExternalPortForwarding"
[2021-03-04 10:40:18.639 +01:00] [INF] [2] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[2021-03-04 10:40:18.643 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "LibraryChangedNotifier"
[2021-03-04 10:40:18.645 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "RecordingNotifier"
[2021-03-04 10:40:18.647 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UdpServerEntryPoint"
[2021-03-04 10:40:18.650 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "UserDataChangeNotifier"
[2021-03-04 10:40:18.653 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DlnaEntryPoint"
[2021-03-04 10:40:18.655 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpDevicePublisher
[2021-03-04 10:40:18.764 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing PlayToManager
[2021-03-04 10:40:18.766 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
[2021-03-04 10:40:18.768 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
[2021-03-04 10:40:18.770 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing _BroadcastListenSocket
[2021-03-04 10:40:18.772 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" Disposing 3 sendSockets
[2021-03-04 10:40:18.774 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "0.0.0.0"
[2021-03-04 10:40:18.775 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "192.168.1.33"
[2021-03-04 10:40:18.777 +01:00] [INF] [2] Emby.Dlna.Main.DlnaEntryPoint: "SsdpCommunicationsServer" disposing sendSocket from "192.168.56.1"
[2021-03-04 10:40:18.779 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "NotificationEntryPoint"
[2021-03-04 10:40:18.782 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "EntryPoint"
[2021-03-04 10:40:18.784 +01:00] [INF] [2] Emby.Server.Implementations.ApplicationHost: Disposing "DeviceAccessEntryPoint"

**Comment by Bandid0** [comment] 2021-03-04 09:51
https://user-images.githubusercontent.com/79402382/109945238-57560480-7cd7-11eb-983d-9977e02b95dd.mp4


clicking on the download icon turns blue and does nothing else

**Comment by chrstfer** [comment] 2021-03-05 00:57
Those look like startup logs for jellyfin, but we need logs that include the time you attempt to download something. Please attempt to download a book a few times (multiple books preferably) then immediately go to the logs page in the dashboard options and paste the entirety of the most recent log file there. 

Also, please put long pastes like logs into a gist and link that, rather than pasting them directly into the issue thread. 

Thanks.

**Comment by Bandid0** [comment] 2021-03-05 10:16
in tried to download an audiobook and if you have downloaded it.
In reference to the registry, it is what it does there is nothing else with ebooks and with audiobooks, it does not generate any error log

**Comment by rafe101** [comment] 2021-08-14 14:18
Just wanted to jump on this to say I'm having the same issue. There's nothing in the logs. It's like I never push the button except that it turns blue

**Comment by Banh-Canh** [comment] 2021-11-01 17:08
Hello, I can confirm that I have the same issue using the android app.

**Comment by bckncook** [comment] 2022-02-11 14:10
Same. Clicking download link in app does nothing... button just turns blue for a bit, but nothing else, and no file to be found. Opening the same page in a browser on same device and clicking the same button downloads file correctly and it comes right up in external reader after clicking open. 

As a related aside, until the built in reader in the app is more refined, sure would be great if you could set the app to automatically open books in an external reader, just as you can set it to open videos in an external player.

**Comment by jacktheripper19** [comment] 2022-02-20 23:49
> Same. Clicking download link in app does nothing... button just turns blue for a bit, but nothing else, and no file to be found. Opening the same page in a browser on same device and clicking the same button downloads file correctly and it comes right up in external reader after clicking open.
> 
> As a related aside, until the built in reader in the app is more refined, sure would be great if you could set the app to automatically open books in an external reader, just as you can set it to open videos in an external player.

Can't agree more. The built-in reader is quite useless now, you can't even select text from the books

**Comment by djosiahwright** [comment] 2022-05-26 06:25
I'm having the same issue. I hit the download button it turns blue and then nothing happens until it turns grey again.

**Comment by PizzaCoder** [comment] 2022-05-26 09:22
Can we please try to fix this? The built in reader is far from perfect and I would like at least a basic "file server" functionality for my books within Jellyfin. It only happens on Android, works fine on the Web client.

**Comment by bckncook** [comment] 2022-07-25 13:47
Any updates planned or in progress for download issue or external reader support?

**Comment by nielsvanvelzen** [comment] 2022-07-25 14:01
If someone could share logs we can look into the issue. I don't have any books in my server so I can't reproduce the issue.

**Comment by bckncook** [comment] 2022-07-25 14:05
What is the Android path and name for the log you need? If you need anything from the server side as well, let me know the same for that. Thank you!

**Comment by bckncook** [comment] 2022-07-25 18:11
Got the logs. Would rather PM them to you since they're so much broader than just jellyfin. Didn't realize you needed a system-wide log. Sorry, first time doing any of this here. Thanks for your help!

You mentioned jellyfin-web, so if relevant, remember that it does fine in browser: "Clicking download link in app does nothing... button just turns blue for a bit, but nothing else, and no file to be found. Opening the same page in a browser on same device and clicking the same button downloads file correctly and it comes right up in external reader after clicking open."

**Comment by nielsvanvelzen** [comment] 2022-07-25 20:08
> Got the logs. Would rather PM them to you since they're so much broader than just jellyfin. Didn't realize you needed a system-wide log. Sorry, first time doing any of this here. Thanks for your help!

You can send them to me on [Matrix](https://matrix.to/#/@nielsvanvelzen:matrix.org) or look for a line that starts with "Download failed: " and copy the section around it.

> You mentioned jellyfin-web, so if relevant, remember that it does fine in browser: "Clicking download link in app does nothing... button just turns blue for a bit, but nothing else, and no file to be found. Opening the same page in a browser on same device and clicking the same button downloads file correctly and it comes right up in external reader after clicking open."

The app tells the web interface it can take over some features, we do this for downloads too. So when the download button is pressed the app receives the information to start the download. So that's why it might work on a standalone version of jellyfin-web but not when used from the app.

**Comment by nielsvanvelzen** [comment] 2022-07-26 15:48
Ok so the issue is in jellyfin-web. We expect 3 fields when a download is requested: title, filename and url.

https://github.com/jellyfin/jellyfin-android/blob/b0f378891bc3557736f43259e7c8c2cd8cf8f36b/app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt#L151-L168

But jellyfin-web returns the wrong data in 2 places; the slideshow component and the item details page:

- https://github.com/jellyfin/jellyfin-web/blob/8e0572337778fa18e132bb443e21d6d9f408c7ad/src/controllers/itemDetails/index.js#L1983-L1990
  Missing title and filename
- https://github.com/jellyfin/jellyfin-web/blob/8e0572337778fa18e132bb443e21d6d9f408c7ad/src/components/slideshow/slideshow.js#L478
  Missing title and filename in imageInfo

It could be fixed in 2 ways; either by not requiring the title and filename or by adding them in jellyfin-web.

**Comment by nielsvanvelzen** [comment] 2022-07-27 13:40
Status update: a fix should be released in 10.8.2 (no ETA). The pull request for the fix is linked above this comment, this issue will auto-close when the pull request is merged.

**Closed** 2022-07-27 14:44 UTC
Labels: bug
