### ISSUE TITLE
Audio stuttering on FLAC files only

### ISSUE THREAD

**Issue by fubka** [jellyfin/jellyfin-android#741] opened 2022-07-21 21:28 UTC
### Describe the bug

1.  Open a FLAC file and listen.
2.  FLAC audio files will pause or stutter.
3.  FLAC files do not have ID3 tags.
4. If I use a different client like Finamp or Gelli, I do not get the stuttering.

### Logs

/Audio/84b2613b9de181fd0dde51071e08820e/hls1/main/0.ts

{"Protocol":0,"Id":"84b2613b9de181fd0dde51071e08820e","Path":"/home/pi/music/Green Day Dooke Vinyl 2009/01-green_day-burnout.flac","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"flac","Size":49311296,"Name":"01-green_day-burnout","IsRemote":false,"ETag":"707143328422567190ccc6be8d98fb88","RunTimeTicks":1274590848,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"flac","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/96000","CodecTimeBase":"1/96000","Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"FLAC - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":3095035,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":96000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":3095035,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/bin/ffmpeg -analyzeduration 200M  -i file:"/home/pi/music/Green Day Dooke Vinyl 2009/01-green_day-burnout.flac" -map_metadata -1 -map_chapters -1 -threads 0   -acodec aac -ab 256000 -ac 2 -vn -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c.m3u8"

ffmpeg version 4.1.8-0+deb10u1+rpt1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
  WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avcodec     configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avformat    configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avdevice    configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avfilter    configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avresample  configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swscale     configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swresample  configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  postproc    configuration: --prefix=/usr --extra-version=0+deb10u1+rpt1 --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from 'file:/home/pi/music/Green Day Dooke Vinyl 2009/01-green_day-burnout.flac':
  Metadata:
    LANGUAGE        : English
    track           : 1
    TITLE           : Burnout
    RIP DATE        : 2020-04-04
    DATE            : 2009
    RETAIL DATE     : 2009-00-00
    MEDIA           : LP
    ENCODED BY      : .:WRE:.
    SUPPLIER        : .:WRE:.
    ENCODER         : FLAC 1.3.1
    RIPPING TOOL    : Adobe Audition 2020
    RELEASE TYPE    : Reissue
    GENRE           : Punk Rock
    ORGANIZATION    : Reprise Records
    CATALOG         : 9362-49869-5
    ARTIST          : Green Day
    ALBUM           : Dookie
  Duration: 00:02:07.46, start: 0.000000, bitrate: 3068 kb/s
    Stream #0:0: Audio: flac, 96000 Hz, stereo, s32 (24 bit)
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c0.ts' for writing
[mpegts @ 0xdfdba0] frame size not set
Output #0, hls, to '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c.m3u8':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Audio: aac (LC), 96000 Hz, stereo, fltp (24 bit), 256 kb/s
    Metadata:
      encoder         : Lavc58.35.100 aac
size=N/A time=00:00:02.58 bitrate=N/A speed=5.14x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c1.ts' for writing
size=N/A time=00:00:05.09 bitrate=N/A speed=5.05x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c2.ts' for writing
size=N/A time=00:00:07.44 bitrate=N/A speed=4.91x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c3.ts' for writing
size=N/A time=00:00:09.92 bitrate=N/A speed=4.91x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c4.ts' for writing
size=N/A time=00:00:12.56 bitrate=N/A speed=4.98x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c5.ts' for writing
size=N/A time=00:00:15.25 bitrate=N/A speed=5.03x    
size=N/A time=00:00:17.94 bitrate=N/A speed=5.07x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c6.ts' for writing
size=N/A time=00:00:20.54 bitrate=N/A speed=5.09x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c7.ts' for writing
size=N/A time=00:00:23.14 bitrate=N/A speed=5.08x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c8.ts' for writing
size=N/A time=00:00:25.79 bitrate=N/A speed= 5.1x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c9.ts' for writing
size=N/A time=00:00:28.39 bitrate=N/A speed= 5.1x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c10.ts' for writing
size=N/A time=00:00:30.99 bitrate=N/A speed=5.11x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c11.ts' for writing
size=N/A time=00:00:33.30 bitrate=N/A speed=5.07x    
size=N/A time=00:00:35.94 bitrate=N/A speed=5.08x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c12.ts' for writing
size=N/A time=00:00:38.50 bitrate=N/A speed=5.08x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c13.ts' for writing
size=N/A time=00:00:41.06 bitrate=N/A speed=5.08x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c14.ts' for writing
size=N/A time=00:00:43.66 bitrate=N/A speed=5.08x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c15.ts' for writing
size=N/A time=00:00:46.31 bitrate=N/A speed=5.09x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c16.ts' for writing
size=N/A time=00:00:48.87 bitrate=N/A speed=5.09x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c17.ts' for writing
size=N/A time=00:00:51.47 bitrate=N/A speed=5.09x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c18.ts' for writing
size=N/A time=00:00:54.03 bitrate=N/A speed=5.09x    
size=N/A time=00:00:56.64 bitrate=N/A speed= 5.1x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c19.ts' for writing
size=N/A time=00:00:59.24 bitrate=N/A speed= 5.1x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c20.ts' for writing
size=N/A time=00:01:01.88 bitrate=N/A speed=5.11x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c21.ts' for writing
size=N/A time=00:01:04.57 bitrate=N/A speed=5.11x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c22.ts' for writing
size=N/A time=00:01:07.26 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c23.ts' for writing
size=N/A time=00:01:09.90 bitrate=N/A speed=5.13x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c24.ts' for writing
size=N/A time=00:01:12.46 bitrate=N/A speed=5.13x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c25.ts' for writing
size=N/A time=00:01:15.02 bitrate=N/A speed=5.12x    
size=N/A time=00:01:17.50 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c26.ts' for writing
size=N/A time=00:01:20.19 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c27.ts' for writing
size=N/A time=00:01:22.83 bitrate=N/A speed=5.13x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c28.ts' for writing
size=N/A time=00:01:25.31 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c29.ts' for writing
size=N/A time=00:01:27.91 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c30.ts' for writing
size=N/A time=00:01:30.47 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c31.ts' for writing
size=N/A time=00:01:33.07 bitrate=N/A speed=5.12x    
size=N/A time=00:01:35.68 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c32.ts' for writing
size=N/A time=00:01:38.24 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c33.ts' for writing
size=N/A time=00:01:40.97 bitrate=N/A speed=5.13x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c34.ts' for writing
size=N/A time=00:01:43.70 bitrate=N/A speed=5.13x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c35.ts' for writing
size=N/A time=00:01:46.34 bitrate=N/A speed=5.14x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c36.ts' for writing
size=N/A time=00:01:49.03 bitrate=N/A speed=5.14x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c37.ts' for writing
size=N/A time=00:01:51.68 bitrate=N/A speed=5.14x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c38.ts' for writing
size=N/A time=00:01:54.36 bitrate=N/A speed=5.15x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c39.ts' for writing
size=N/A time=00:01:57.05 bitrate=N/A speed=5.15x    
size=N/A time=00:01:59.74 bitrate=N/A speed=5.16x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c40.ts' for writing
size=N/A time=00:02:02.43 bitrate=N/A speed=5.16x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c41.ts' for writing
size=N/A time=00:02:05.16 bitrate=N/A speed=5.17x    
[hls @ 0xd883f0] Opening '/root/.local/share/jellyfin/transcodes/42dac5f03a1cff4a7ae6114df729aa7c42.ts' for writing
size=N/A time=00:02:06.65 bitrate=N/A speed=5.12x    
[hls @ 0xd883f0] Cannot use rename on non file protocol, this may lead to races and temporary partial files
size=N/A time=00:02:07.46 bitrate=N/A speed=5.05x    
video:0kB audio:3992kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[aac @ 0xd8a020] Qavg: 822.688

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Google Pixel 3a

### Android version

Android 12

### Jellyfin server version

10.8.1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment] 2022-07-22 07:12
Duplicate of #39.

**Closed** 2022-07-22 07:12 UTC
Labels: bug, duplicate
