### ISSUE TITLE
App closes when back button pressed! 

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin-android#229] opened 2020-11-08 04:32 UTC
**Describe the bug**

When I press back (not in app, in my phone) the app closes

**To Reproduce**

1. Install 2.1.3
2. Open and browse
3. From a Season/Episode/Movie info page, press back on phone

**Expected behavior**

Go to the previous screen 
**Logs**

**Screenshots**

**System (please complete the following information):**
 - App version: 2.1.3 proprietary 
 - Android version: 10
 - Device manufacturer and model: Realme X2 (CN)
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: WEB PLAYER, (exo or system doesn’t work, transcode is never done there, only black screen!)

**Additional context**

None

**Comment by Maxr1998** [comment] 2021-05-24 22:39
This works on the latest server & app version. There were issues once caused by a bug in the web client, those are resolved now. Closing.

**Closed by Maxr1998** 2021-05-24 22:39 UTC
Labels: bug

**Comment by Mvne** [comment] 2022-09-19 20:42
Although this is closed. This behavior still happens on my android device. Galaxy s21, android 12. App version 2.4.4

**Comment by Maxr1998** [comment] 2022-09-20 11:54
Does this happen from every screen?

**Comment by Mvne** [comment] 2022-09-20 15:15
> Does this happen from every screen?

Yes, unfortunately 😔  I must add here that I do not contribute to this project. I'm just an enthusiastic user!

**Comment by Maxr1998** [comment] 2022-09-21 21:30
Understood, no worries about that. I believe it might be related to your phone and your Android/Browser version. Could you give us a few details about your setup please?

**Comment by Mvne** [comment] 2022-09-23 13:19
Thanks! Currently I'm on a Samsung Galaxy s21 running Android 12, with their OneUI 4.1 layer. I use two browsers: their native Samsung Internet app, version 18.0.0.58. And Chrome version 105.0.5195.136.
If you need to know more, please let me know!

**Comment by Kentronix57** [comment] 2022-10-13 02:56
Hello, I am also experiencing this behavior. It does happen on every screen (Ex, Seasons, Movies, Episodes pages...)
Below are my details, if I missed anything, please let me know!

App version: 2.4.4 proprietary app, installed from playstore.
Android version: 12 
One UI version: 4.1.1
Device manufacturer and model: Samsung Galaxy Z Fold 3
Jellyfin server version: 10.8.5
The type of video player implementation used: External Player (MX Player Pro, best compatibility for me, so, less transcoding!)

**Comment by kankaristo** [comment] 2023-04-04 12:23
This is still an issue, but it only happens for me in a specific situation. Sometimes, Android's bottom navigation bar (the one with the back button) becomes semi-transparent and is shown on top of the Jellyfish UI (but not on top of other apps). It also partially blocks the player / playback controls at the bottom. Normally, it has a black background and is not on top of the UI.

Only in this bugged-out mode, the back button moves the app to the background. Closing and re-opening the app (and not just moving it to the background) fixes the issue. I'm not sure how it happened, I can't reproduce currently...

App version: 2.4.4 (installed from Google Play)
Server version: 10.8.9
OS: Android 13
UI: OneUI 5.1 / Nova Launcher 7.0.57
Device: Samsung Galaxy A52s 5G

**Comment by ivanmolenaar** [comment] 2025-02-19 11:10
This is still an issue for me on my Samsung S23 Ultra with:
app version: 2.6.2
Android version: 14

**Comment by NicholasFreeman** [comment] 2025-05-10 01:34
This is still an issue.

 On fresh app start, things are usually fine. After the app is backgrounded or otherwise looses focus (screen lock), it _may_ exhibit this behaviour.

Restarting the app temporarily fixes the problem. 

Pixel 9 Pro XL
Android 15
Jellyfin for Android: 2.6.2
Jellyfin server: 10.10.7 (docker)
