### ISSUE TITLE
Google Cast Unsupported on Motorola Edge 30

### ISSUE THREAD

**Issue by ryannathans** [jellyfin/jellyfin-android#1147] opened 2023-08-05 10:41 UTC
### Describe the bug

1. install jellyfin from google play
2. open app
3. connect to server via https
4. click cast button
5. see "(Google Cast Unsupported)"

if I repeat the same steps on a friend's phone (on the same network) it works as expected

when I build master and debug it on both phones, I notice the working phone receive setup and initialise CastMessage events on app start but on my phone a breakpoint in ActivityEvent.CastMessage (line 78 in app/src/main/java/org/jellyfin/mobile/events/ActivityEventHandler.kt) does NOT get hit when following repro steps above

google cast works on all other apps on my phone, including emby

I made a forum thread and 2 other users with the same phone have the same problem: https://forum.jellyfin.org/t-google-cast-unsupported

### Logs

git master debug build logcat: http://ix.io/4Crn
google play store build logcat: http://ix.io/4Cs8

### Application version

2.5.2

### Where did you install the app from?

Google Play

### Device information

Motorola Edge 30

### Android version

Android 13, Lineage OS 20 nightly

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by ryannathans** [comment] 2023-08-05 13:24
this is an interesting regular part of my logs from repros

```
08-05 23:17:45.981 29562 29562 I CastService: [instance-90] [com.google.android.gms] Connected to device. rejoinedApp: true
08-05 23:17:45.983 29562  3795 E CDC|API|102: [controller-0102-com.google.android.gms API] sendTextMessage - Text message has no destination ID. Message discarded.
08-05 23:17:45.983 29562  3795 I CastService: [instance-90] [com.google.android.gms] onMessageSendFailed: urn:x-cast:com.google.cast.media 2 INVALID_REQUEST
08-05 23:17:46.013 29562 29562 I CastMediaRouteProvider: Published 4 routes
08-05 23:17:46.013 29562  4900 I CastService: [instance-90] [com.google.android.gms] onApplicationConnected: applicationId: 233637DE, name: YouTube, namespaces.count: 4, senderAppIdentifier: null, senderAppLaunchUrl: null, iconUrl: , type: ANDROID_TV Youtube 9dbd571b-6900-4d3e-85c5-2a20cd2a859b false
08-05 23:17:46.013 29562 29562 I CastMediaRouteProvider: Published 4 routes
08-05 23:17:46.015  1623  1623 I MR2ServiceImpl: addProviderRoutes | provider: com.google.android.gms/.cast.media.CastMediaRoute2ProviderService_Persistent, routes: [e43e2091-f3ff-48f5-aa7f-d35d1ecd1111 | Naked Girl TV]
```

**Comment by minigt** [comment] 2023-08-10 01:50
can confirm, same issue on moto edge 30. Other apps are able to cast.

**Comment by ryannathans** [comment] 2023-08-10 02:24
> can confirm, same issue on moto edge 30. Other apps are able to cast.

What OS version do you have running on your phone?

**Comment by minigt** [comment] 2023-08-10 02:55
Android 13

**Comment by minigt** [comment] 2023-08-10 03:24
this funtion
`async execCast(action, args, callback) {`
on nativeshell.js is not being called, so the setup and initialize events are never trigger. But I don't know who is suppose to call that funtion...

**Comment by ryannathans** [comment] 2023-08-10 03:27
there are no CastMessages received for the events, but I don't know what is supposed to generate these CastMessages

maybe there is something wrong with how the chromecast objects get initialised

**Comment by minigt** [comment] 2023-08-10 03:36
mm, if I put a breakpoint on the interceptor on the chrome.cast.js line, that line is hit by my phone that can cast, but on the moto edge that line is never hit

`path.endsWith(Constants.CAST_SDK_PATH) -> {
                assetsPathHandler.inject("native/chrome.cast.js")
            }
`

so looks like the file that emits the setup and initialize events is not being injected on edge

**Comment by ryannathans** [comment] 2023-08-10 04:06
I'm curious about this bit
>08-05 23:17:45.983 29562  3795 E CDC|API|102: [controller-0102-com.google.android.gms API] sendTextMessage - Text message has no destination ID. Message discarded.
08-05 23:17:45.983 29562  3795 I CastService: [instance-90] [com.google.android.gms] onMessageSendFailed: urn:x-cast:com.google.cast.media 2 INVALID_REQUEST

**Comment by minigt** [comment] 2023-08-10 04:13
I think you are on to something. I just try a couple of things and I notice I can see my other phone from moto Edge, although when I try to cast something it freezes, but at least it recognizes it, so only my chromcast device is unreachable

**Comment by minigt** [comment] 2023-08-10 04:15
btw, where do you se that log? on logcat? I don't see anything like it on my side

**Comment by ryannathans** [comment] 2023-08-10 04:16
yeah that's in my logcat for the **google play build** of jellyfin each time I open the app and click the cast button

**Comment by minigt** [comment] 2023-08-10 04:27
I don't get those, neither on the google play build nor cloning master and debugging on android studio

**Comment by ryannathans** [comment] 2023-08-10 04:28
maybe the logs are a red herring then, or related to some specific chromecast device on my network

**Comment by minigt** [comment] 2023-08-10 04:33
sorry, my bad, I did't increase the logging level. I am getting them now, so I wouldn't dissmis them as read herrings yet

**Comment by minigt** [comment] 2023-08-10 18:32
https://github.com/jellyfin/jellyfin-web/blob/26b83efc95f24ddc10c595d8e472682342764d0b/src/apps/experimental/components/AppToolbar/menus/RemotePlayMenu.tsx#L68

I found this, to add a bit o context.

**Comment by minigt** [comment] 2023-08-10 18:36
and this
https://github.com/jellyfin/jellyfin-web/blob/26b83efc95f24ddc10c595d8e472682342764d0b/src/components/playback/playerSelectionMenu.js#L107

**Comment by minigt** [comment] 2023-08-11 02:30
I found it. The issue is not on the android app, is on jellifin-web. I'll add a fix

**Comment by Maxr1998** [comment] 2023-09-28 16:59
Fixed in Jellyfin Web.

**Closed** 2023-09-28 16:59 UTC
Labels: bug, upstream, confirmed
