### ISSUE TITLE
bottom play bar doesn't hide

### ISSUE THREAD

**Issue by osias10** [jellyfin/jellyfin-android#379] opened 2020-07-27 03:48 UTC
when I play a video with android jellyfin app, if I click the setting button(gear icon), then bottom play bar never hide

**Comment by dmitrylyzo** [comment] 2020-07-28 17:55
Do you just open preferences and leave popup (preferences) open?

**Comment by ThibaultNocchi** [comment] 2020-07-30 06:55
I do have the same problem when selecting a different resolution than the one I loaded the player with. If I open the gear menu, playback info or simply opening the resolutions menu, it's fine. Once I change resolution, the overlay won't disappear. But it also happens in mobile Chrome (not FF).

**Comment by Jerk-Solutions** [comment] 2020-08-04 15:33
Same problem when pausing video. It doesn't go away unless the playback is stopped and started again

**Comment by thornbill** [comment] 2020-08-12 14:21
This seems to be a duplicate of #377

**Closed by thornbill** 2020-08-12 14:21 UTC
