### ISSUE TITLE
No subtitles in mkv

### ISSUE THREAD

**Issue by michalszymura** [jellyfin/jellyfin-android#279] opened 2020-03-02 20:03 UTC
Subtitles stopped working in android app after upgrading from v0.9.5 to v0.9.9.
Server Version: 10.4.3

**Comment by Artiume** [comment] 2020-03-05 19:06
Core issue is a duplicate of https://github.com/jellyfin/jellyfin-android/issues/258

**Closed** 2020-03-05 19:34 UTC
