### ISSUE TITLE
Subtitles on exoplayer

### ISSUE THREAD

**Issue by Altereno** [jellyfin/jellyfin-android#82] opened 2020-08-31 02:35 UTC
Subtitles get displayed in a black text box, it would be nice for just the text to appear over the video.

**Comment by Maxr1998** [comment] 2020-08-31 06:32
You can customize how substitles are displayed in the Android settings. There's a section in the accessibility options.
See here: ![Screenshot](https://user-images.githubusercontent.com/5903699/91689464-7925d180-eb64-11ea-8206-f621443fa097.jpg)

**Comment by Maxr1998** [comment] 2020-08-31 06:33
Also, duplicate of #42.

**Closed** 2020-08-31 06:33 UTC
Labels: duplicate, exoplayer, question
