### ISSUE TITLE
Can't transcode music

### ISSUE THREAD

**Issue by oonqt** [jellyfin/jellyfin-android#214] opened 2019-10-19 05:42 UTC
If I set my music quality setting to something below that of the source audio and try to play the audio, the server gives an error saying "No compatible streams are available". 

Server: 10.4.0
Android app version: 0.9.4

**Comment by pwetzel** [comment] 2019-10-21 20:23
Duplicate of #135.

**Closed** 2019-10-21 21:57 UTC
Labels: duplicate
