### ISSUE TITLE
JellyFin audio stuttering when mobile device locks

### ISSUE THREAD

**Issue by ma-karai** [jellyfin/jellyfin-android#147] opened 2019-06-11 12:28 UTC
I listen to some FLAC files on the JellyFin App and as soon as the screen locks I can perceive stutters. The same songs does not have this issue with the current emby app, and it stops as soon as I unlock the device.

**Comment by anthonylavado** [comment] 2019-06-11 16:33
Hrm. Do you have battery optimization disabled for the Jellyfin app?

**Comment by ma-karai** [comment] 2019-06-12 12:35
I tried with and without the battery saver mode, still the same issues.

**Comment by anthonylavado** [comment] 2019-06-13 00:46
OKay. Just to help the client team gather some more information:
* What model phone do you have?
* What version of Android & System Webview do you have?
* Does this happen with other audio formats?

**Comment by ma-karai** [comment] 2019-06-13 07:26
Its a Xiaomi Redmi Note 5
Android 9 pkq1 180904.001, latest system webview form the store updated may 19th.
Yes happens with mp3s as well.

**Comment by dkanada** [comment] 2019-06-19 06:34
@ma-karai this seems to be a common issue with the app. I actually thought it had been fixed when we removed an old dependency. We have an ExoPlayer implementation in the works that might be a workaround, but it isn't quite ready yet.

**Comment by dkanada** [comment] 2019-06-19 06:36
Since this is a duplicate I will close it in favor of #134, let me know if you can find a reliable way to reproduce the clicking.

**Closed by dkanada** 2019-06-19 06:36 UTC
Labels: bug

**Comment by steelwolf** [comment] 2019-09-12 04:07
>  let me know if you can find a reliable way to reproduce the clicking.
I can reproduce it pretty reliably by playing an mp3 file with the Jellyfin app and then switching to any other app as foreground, turning off the screen, or locking the device.

- Battery optimizations disabled
- Google Pixel 2 XL
- Android 10 (QP1A.190711.020)
