### ISSUE TITLE
Is there no cache in the app?

### ISSUE THREAD

**Issue by AhatLi** [jellyfin/jellyfin-android#386] opened 2020-08-07 06:30 UTC
Some streaming music player applications have a cache.
The cache settings include the capacity of the cache and the count of files to be cached, and the next file in the playlist is downloaded in advance according to the capacity and count.

When I used the jellypin app, as soon as the network connection was lost, the music stopped playing and the next file was also unable to play.
Also, I couldn't find items related to the cache in the config.
I don't think the cache function exists is it correct?

I think this application will be great if you add a cache.

**Comment by nielsvanvelzen** [comment] 2020-08-07 06:33
Duplicate of #385

**Closed by nielsvanvelzen** 2020-08-07 06:33 UTC
