### ISSUE TITLE
Make audiobooks available for Android Auto

### ISSUE THREAD

**Issue by teacupx** [jellyfin/jellyfin-android#314] opened 2021-03-02 17:13 UTC
**Describe the feature you'd like**
Right now, only collections of type "Music" are shown in Android Auto. Showing also "Books" collections would be very useful for people who listen to audiobooks on their way to work or their travels.

**Additional context**
Audiobooks collections are meant to be organized in folders, instead of browsing through artists/albums. This needs to be taken into account.

**Comment by nielsvanvelzen** [comment] 2021-03-02 17:16
Duplicate of #247

**Closed by nielsvanvelzen** 2021-03-02 17:16 UTC
Labels: enhancement

**Comment by teacupx** [comment] 2021-03-02 17:19
Sorry, I did a search but that one didn't show up :)
