### ISSUE TITLE
Lower minimum android version

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin-android#173] opened 2019-08-05 11:24 UTC
Currently Emby from GP can be installed on my tablet with android 4.4, but jellyfin is not available in search results. Would you please lower minimum requirements?

**Comment by thornbill** [comment] 2019-08-13 13:59
I’m afraid this isn’t a simple request. The Android app relies on jellyfin-web which uses a lot of features that aren’t supported in the Android webview of older devices. A couple of us have tried adding support (via polyfills) in the past but weren't very successful.

**Comment by 1xPdd** [comment] 2019-09-22 13:07
Curious what the version requirements are? I was surprised to see that LineageOS 14.1, which is Android 7.1, became unsupported in the move from Emby to Jellyfin. 14.1 came out in 2017, so it's not terribly old. Obviously it would be great if we could support more devices/users, even if that isn't as far back as 4.4, and I'm sure users of older devices would be happy if they could partially use the application, even if some features didn't work. Could someone say a little more about what features/aspects make older versions of Android so problematic?

**Comment by 1xPdd** [comment] 2019-09-22 13:14
Sorry, just to add a little context. I have Jellyfin 9.0 running fine on LOS 14.1. There are a few bugs but for the most part it works. Something changed in the 9.1 apk that made it impossible to upgrade.

**Comment by anthonylavado** [comment] 2019-09-22 15:18
Hmm that’s interesting. I have a device running Android 6.0.1, and it works for me.

I know in 0.9.2 had a Bluetooth related update. Perhaps that’s related in your case?

**Comment by 1xPdd** [comment] 2019-09-22 17:58
My bad. I completely don't know what I'm talking about, sorry.

Although I wasn't able to upgrade (on three different devices), uninstalling and re-installing 9.4 works fine. As always, the Jellyfin upgrades are a delight. Thanks.

**Comment by thornbill** [comment] 2019-09-22 18:09
We should support anything with Android 5.0 (API level 21) or higher currently.

**Comment by thornbill** [comment] 2019-09-25 14:45
Duplicate of #28

**Closed by thornbill** 2019-09-25 14:45 UTC
