### ISSUE TITLE
Cannot upload user profile picture

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [jellyfin/jellyfin-android#945] opened 2023-01-03 10:09 UTC
### Describe the bug

1. Connect to a server and login
2. Go to your user profile (also works when editing others' profiles from the dashboard)
3. Tap on the profile picture to upload a new one
4. Nothing happens

Instead, I expect the OS picture chooser to appear, like the web version does.

### Logs

[https://gist.github.com/GeoffreyCoulaud/1305c08723922cc9c97f6b50670c0999](https://gist.github.com/GeoffreyCoulaud/1305c08723922cc9c97f6b50670c0999)

### Application version

2.4.4

### Where did you install the app from?

Google Play Store

### Device information

Oppo A94 5G

### Android version

Android 12

### Jellyfin server version

10.8.5

### Which video player implementations does this bug apply to?

(Not applicable)

**Comment by nielsvanvelzen** [comment] 2023-03-20 20:22
Closing this one as duplicate of #945 since both issues are caused by the same problem.

**Closed by nielsvanvelzen** 2023-03-20 20:22 UTC
Labels: bug
