### ISSUE TITLE
Occasional audio cuts and lags when app is playing music in background

### ISSUE THREAD

**Issue by orhanarifoglu** [jellyfin/jellyfin-android#240] opened 2020-01-09 11:40 UTC
Hi , I am using Xiaomi Mi 9t pro. I tried all releases so far. All of them has issue I described in title. Normal playback is perfect but soon as I switch to different app or lock the screen audio starts to become inconsistent and laggy. I have battery optimization turned off. Tried jellyfin on browser and it works normally so suspect it  is app issue.

**Comment by JustAMan** [comment] 2020-01-10 15:23
Duplicate of https://github.com/jellyfin/jellyfin-android/issues/134

**Closed** 2020-01-10 15:23 UTC
Labels: duplicate
