### ISSUE TITLE
ExoPlayer doesn't follow skip forward/back length

### ISSUE THREAD

**Issue by MBR-0001** [jellyfin/jellyfin-android#429] opened 2021-06-14 11:08 UTC
**Describe the bug**
Tapping twice on any side of the screen skips back/forward 5 seconds, regardless of `Skip forward length` and `Skip back length` in `Playback`

**To Reproduce**
1. Open any video file
2. Tap twice on right side of screen
3. The video skips forward 5 seconds

**Expected behavior**
The video should skip forward/back the set amount of seconds

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - App version: 2.3.0-beta.3
 - Android version: 11 (LineageOS 18.1)
 - Device manufacturer and model: OnePlus 3T
 - Jellyfin server version: 10.7.5
 - The type of video player implementation used: native player (ExoPlayer)

**Additional context**
Issue doesn't occur when using the web player (it follows the settings)

**Comment by Maxr1998** [comment] 2021-06-14 11:34
Duplicate of #84.

**Closed** 2021-06-14 11:34 UTC
Labels: bug, duplicate
