### ISSUE TITLE
[Feature Request] Allow Download or Offline Sync for mobile devices and other features request.

### ISSUE THREAD

**Issue by ruCyberPoison** [jellyfin/jellyfin-android#270] opened 2020-02-24 17:27 UTC
Hello everyone, i leave here some feature to appear if someone volunteer to do that, since jellyfin for Android is open source, this is some feature can be cool.

[1] - Download and convert content to your mobile with the metada to allow us to read the Metadata (Synopsis, poster etc..) to your device, with a progress bar and category to show us in how many time it will be ok.

[2] - Exoplayer as the native player for the mobile app so to allow hevc, Hdr10, etc.. Codecs. (Apparently in progress...)

[3] - Allow direct play/Original Quality as an option in the Quality settings (In the playback player and in the setting to be set as default) .

[4] - Upload Pictures from your mobile to the Jellyfin Server,

[5] - Play Musical themes in the movie/TV when available.
It all for my atm, feel free to improve some of this features to the mobile app and other apps.

Kind regards.

**Comment by JustAMan** [comment] 2020-02-26 14:18
Feature requests are tracked here: https://features.jellyfin.org/
And there's no use of stuffing all you can think of in a single issue.

Now, 1 is one of most requested, and will be done when someone wants to.
2 is being worked on, albeit slowly.
3 is somewhat unclear - isn't it already doing so?
4 was explicitly removed and we're not wanting to add it to the server (but you can add it as a plugin) - Jellyfin is a media server, not a backup solution or something.
5 requires a source of such metadata and of the musical files. I don't think any open DB exists that we can use.

**Comment by ruCyberPoison** [comment] 2020-02-27 01:25
Yes but it's not on the [3] is not in the quality setting, there is no way apparently to force the Original Quality

**Comment by dkanada** [comment] 2020-04-23 03:33
The first one is a duplicate of #55 so you can track updates there. The second can be tracked on the open PR in this repository, and the fourth we don't plan to support. Number three and five would be web features so feel free to search that repository for open issues regarding your suggestions, or open one if they don't yet exist.

**Closed by dkanada** 2020-04-23 03:33 UTC
