### ISSUE TITLE
Syncplay not working with kotlin prerelease v2.3.0-beta 1

### ISSUE THREAD

**Issue by exalented** [jellyfin/jellyfin-android#385] opened 2021-05-12 23:58 UTC
**Describe the bug**
syncplay doesn't work with the kotlin pre release.

**To Reproduce**
1. install the pre release (libre or proprietary)
2. Try to join a group
3. Friend is sad their music stops playing, waiting for your device to 'catch up' but never does.

**Expected behavior**
Syncplay to function like it does with v2.2.3.

**Logs**

***Can't open session***
[jf_kotlin_beta1_videotest.txt](https://github.com/jellyfin/jellyfin-android/files/6469603/jf_kotlin_beta1_videotest.txt)
[jf_kotlin_beta1_audiotest.txt](https://github.com/jellyfin/jellyfin-android/files/6469604/jf_kotlin_beta1_audiotest.txt)

**System (please complete the following information):**
 - App version: pre release v2.3.0-beta 1
 - Android version: Android 8.1.0
 - Device manufacturer and model: Samsung Galaxy Note 9
 - Jellyfin server version: 10.7.5 (official docker)
 - The type of video player implementation used: All players tested

**Additional context**
This was mainly testing audio playback sync, but video playback yeilded similar results after some brief testing.
Tested with ungoogled chromium 90.0.4430.93 and a rooted Note 9.

Let me know if you need details of the media I was testing with.
Flac for audio
h264 & AAC for video

https://github.com/jellyfin/jellyfin-android/issues/20

**Comment by nielsvanvelzen** [comment] 2021-05-13 06:39
Syncplay is not supported for the native/external players. It will come eventually to the native player but we're waiting until the API is stable first. The web player should work so I'm not sure what happened there, does this issue happen in the web client too?

**Comment by exalented** [comment] 2021-05-13 06:56
Yes

**Comment by nielsvanvelzen** [comment] 2021-05-14 13:53
If the issue also happens in the web client we can't do much about it, it's a jellyfin-web issue then.

**Comment by exalented** [comment] 2021-05-14 15:21
No, the issues does not happen in the web client within the browser. It happens in the web player within the android client only in the new kotlin ask.

**Comment by nielsvanvelzen** [comment] 2021-05-21 18:35
That would make this issue an duplicate of #20.

**Closed by nielsvanvelzen** 2021-05-21 18:35 UTC
Labels: bug

**Comment by exalented** [comment] 2021-06-19 23:00
I've concluded that this is an issue with the Note 9's ROM rather than the jellyfin-android kotlin betas.
Testing with an N910C note 4 running LineageOS 17.1 (Android 10, kernel 3.10.9) yeilds no issues other than what is described as follows and may or may not belong in the other thread: #20 

Restarting the server and then imediatly joining a syncplay group prevents clients from being able to play something. In order for syncplay to function as intended the first time around one must disable syncplay, play something and then join a group.

**Comment by exalented** [comment] 2021-09-06 10:01
For those wondering I've finally gotten around to updating my N960F to Android Q and things are working quite well.
