### ISSUE TITLE
 Can't direct play h265 2160p 10bit HDR files on compatible android phone

### ISSUE THREAD

**Issue by pyypgithub** [jellyfin/jellyfin-android#408] opened 2021-05-25 18:40 UTC
The app forces server transcode unnecessarily and it should not transcode 2160p 10bit HDR since both exoplayer(from play store through smb) and emby app can direct play the same file. This device is also equipped with HDR display. 

When I disable video transcode in user account it reported media cannot be played by this device. It can play hvec 1080p just fine though. 

**System (please complete the following information):**
 - App version:  2.3.0-beta3
 - Android version: Android 11 one Ui 3.1
 - Device manufacturer and model: galaxy s10 lite snapdragon 855
 - Jellyfin server version: 10.7.5 on Pi4
 - using native app

**Comment by exalented** [comment] 2021-08-12 05:21
With the previous kotlin v2.3.0 I wasn't able to play anything through the native player nor external player the app would just crash outright. Now the new kotlin v2.3.1 release is able to play things natively and externally, but unnecessarily transcodes exactly as described in OP's post. I have a Sammy ROM, Note 9 exynos running android 8.1 Oero. My server is the official dockerized 10.7.6.

**Comment by Maxr1998** [comment] 2021-08-12 19:13
A lot of that will change once we include the ExoPlayer ffmpeg extension. Right now, a lot of codecs aren't marked as supported in the app, so the server transcodes. Anyway, I think this issue is a duplicate of #28, so I'm closing this on in favor of the original issue.

**Closed by Maxr1998** 2021-08-12 19:13 UTC
Labels: bug
