### ISSUE TITLE
External Player not working with some codecs

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#125] opened 2020-09-13 16:36 UTC
**Describe the bug**
When selecting the external player option, having VLC or MX installed, it does not recognize them and simply a Playback Error appears.

**Screenshots**

https://imgur.com/m22kYEN

https://imgur.com/ReXDlSj

**System:**
 - App version: [2.0.0-rc.5]
 - Android version: [Android 9]
 - Device manufacturer and model: [LG K50s]
 - Jellyfin server version: [10.6.4]
 - The type of video player implementation used: [External Player]

**Comment by harry71019** [comment] 2020-09-14 23:34
I found that this issue happens when it's using the player profile from exoplayer. Currently that profile can be wrong and it makes the player do unnecessary transcodes, when this happens, the external player option fails.
One workaround right now is to disable transcoding for that user, so as long as your player(MX/vlc/mpv/...) and phone can direct play the media, the external player function will work.

**Comment by nielsvanvelzen** [comment] 2020-09-15 07:19
If this is indeed caused by the profile it should be fixed by #127

**Comment by CarlosOlivo** [comment] 2020-10-02 23:18
@JulioNahum @harry71019 Any improvement in v2.0.0-rc.8?

**Comment by harry71019** [comment] 2020-10-03 18:58
@CarlosOlivo 
Yes, now the external player option works nicely. I tested some videos and they can direct play on VLC/MX player. Thanks!

**Comment by nielsvanvelzen** [comment] 2020-10-03 19:06
Closing this issue since it seems to be fixed.

**Closed by nielsvanvelzen** 2020-10-03 19:07 UTC
Labels: bug

**Comment by harry71019** [comment] 2020-10-15 19:26
In the newest version 2.0.1 this error occurred again. An invalid play method error shows up. The fix is still to disable transcoding for the user to be able to use external players.

**Comment by CarlosOlivo** [comment] 2020-10-15 20:50
From the [v2.0.0-rc.8 to v2.0.1](https://github.com/jellyfin/jellyfin-android/compare/v2.0.0-rc.8...v2.0.1) version there are no changes that affect external playback. Does it happen with all the videos or only with some? Could you try to install [jellyfin-android-v2.0.0-rc.8-release.apk](https://github.com/jellyfin/jellyfin-android/releases/download/v2.0.0-rc.8/jellyfin-android-v2.0.0-rc.8-release.apk) again and see if it works as before? Any changes to your server recently?

**Comment by harry71019** [comment] 2020-10-15 21:26
@CarlosOlivo I wen back to v2.0.0-rc.8 and the playback still shows an error. No changes had been made to my server, it's been running 10.6.4 on Windows for some time and I don't recall any updates or changes recently.

I did some extra testing with 2.0.1 and found that some files could be played by external players but some not
(These files can all be played by the phone using MX/VLC without using Jellyfin)
CAN:
1080P H264 / FLAC
![image](https://user-images.githubusercontent.com/59645782/96186116-f6d15100-0f08-11eb-8fe5-eda65232f4c0.png)

1080I MPEG2 / AAC-LC
![image](https://user-images.githubusercontent.com/59645782/96186361-52034380-0f09-11eb-9c3b-0220a086a1f3.png)

4K HEVC 60fps / AAC-LC 5.1ch
![image](https://user-images.githubusercontent.com/59645782/96186611-af979000-0f09-11eb-8366-066a57c03723.png)

1080P HEVC / Dolby Digital 5.1ch
![image](https://user-images.githubusercontent.com/59645782/96186819-f8e7df80-0f09-11eb-985a-b04b21364fd4.png)

1080P H264 / PCM
![image](https://user-images.githubusercontent.com/59645782/96186894-17e67180-0f0a-11eb-870a-1c0bceaeed5c.png)


CANNOT:
1080P H264 / AAC-LC
![image](https://user-images.githubusercontent.com/59645782/96186302-3d26b000-0f09-11eb-9fff-5379076c1742.png)

1080P H264 / PCM
![image](https://user-images.githubusercontent.com/59645782/96186536-8e36a400-0f09-11eb-81c6-165f148344e6.png)

I have not found a clear reason of what can be played and which ones error will occur.
Current pattern is that the files that cannot be played all have one same character in their Jellyfin titles (the Japanese kanji 欅), however, when I added this word to the title of other movies they still play normally.
Also, despite them having 欅 in their titles, the path for the movie files are all in English so I'm not sure why this is causing a issue like this. I will try and do some more testing.

**Comment by Maxr1998** [comment] 2020-10-15 22:44
Very weird. I have tried to find a common pattern, but couldn't come up with a reason for these issues. Could you try to pull a logcat when trying to play a title that doesn't work?

**Comment by CarlosOlivo** [comment] 2020-10-15 23:20
Also can you share some server logs? One that has at least:

-  MediaBrowser.Api.Playback.MediaInfoService:  GetPostedPlaybackInfo profile: ...
- MediaBrowser.Api.Playback.MediaInfoService: User policy for ...
- MediaBrowser.Api.Playback.MediaInfoService: Profile: Android External Player, ...  isEligibleForDirectStream: ...

And any unexpected logs that only appear in the event that a playback error occurs

Like this (text preferred, feel free to remove/hide any information that you consider sensitive)
![image](https://user-images.githubusercontent.com/25919231/96194950-18363b00-0f11-11eb-8eb2-aee16a61ac3d.png)

**Comment by nielsvanvelzen** [comment] 2020-10-16 06:53
Side note: Please open a new issue for this

**Comment by harry71019** [comment] 2020-10-16 10:29
@Maxr1998 @CarlosOlivo @nielsvanvelzen 
I will open a new issue with the sever logs, thanks!

**Comment by Maxr1998** [comment] 2020-10-16 10:30
We could also reopen this one, I suppose..

**Comment by harry71019** [comment] 2020-10-16 10:49
I have opened a new issue here: #192
