### ISSUE TITLE
Music playback stutters in background

### ISSUE THREAD

**Issue by TrentSaggus** [jellyfin/jellyfin-android#354] opened 2021-05-04 04:50 UTC
**Describe the bug**
When listening to music and changing to another app (multitasking) or locking the screen the playback becomes stuttered. Higher Bit-rate songs are having stutter gaps of up to 1 second.

**To Reproduce**

1. Play music from remote or local server over WiFi or cellular.
2. switch to another app, or lock the screen.

**Expected behavior**

Playback should continue error free with the app in the background.

**Logs**

N/A

**Screenshots**

N/A

**System (please complete the following information):**
 - App version: [2.2.3
 - Android version: 10.3.7 GM21AA
 - Device manufacturer and model: OnePlus 7Pro
 - Jellyfin server version: 10.7.2
 - The type of video player implementation used: N/A

**Additional context**

N/A

**Comment by Maxr1998** [comment] 2021-05-04 08:11
Duplicate of #39.

**Closed** 2021-05-04 08:11 UTC
Labels: bug, duplicate
