### ISSUE TITLE
Android App no choice to select external player

### ISSUE THREAD

**Issue by AlecHex** [jellyfin/jellyfin-android#302] opened 2020-04-06 03:24 UTC
I have tried everything I could but I am unable to select any external player in the Jellyfin Android app on my Samsung S10+. The option to play from external player is checked but still whenever I try to play it opens with Jellyfin and any audio codec is transcoded/downmixed to MP3. 
Anyone else with the same problem.

**Comment by JustAMan** [comment] 2020-04-10 10:02
That option isn't working AFAIK.

@dkanada we should probably remove it for now to stop confusion, thoughts?

**Comment by dkanada** [comment] 2020-04-23 03:34
I haven't disabled this because it should technically be working but no one has looked into the issues yet, so I'll pin this thread and hope someone is interested in working on the external player.

**Comment by AlecHex** [comment] 2020-04-23 03:37
> 
> 
> I haven't disabled this because it should technically be working but no one has looked into the issues yet, so I'll pin this thread and hope someone is interested in working on the external player.

Thank you for considering. Hope it gets fixed soon, so I can move over to Jellyfin.

**Comment by biaji** [comment] 2020-04-27 10:14
it seemed this function not implemented yet:

```js
        self.play = function (options) {
            return modifyStreamUrl(options).then(function (streamUrl) {
                // TODO reimplement
                return Promise.resolve();
            });
        };
```
Here should be a native implement to send a intent to start an external player.   But maybe it will be difficult to control the player through the jellyfin client.

**Comment by Artiume** [comment] 2020-05-02 11:40
Helpful image for end users related from related ticket.

> ![02](https://user-images.githubusercontent.com/49992475/80535634-b3733c80-89d3-11ea-81b3-923d0b51ac91.jpg)

**Comment by thornbill** [comment] 2020-08-02 04:10
Duplicate of #67.

**Closed by thornbill** 2020-08-02 04:10 UTC
