### ISSUE TITLE
Unable to connect with 1.0.2 in miui 11.0.3

### ISSUE THREAD

**Issue by jakclynn** [jellyfin/jellyfin-android#389] opened 2020-08-12 09:41 UTC
Hello, I have a problem.
At miui 11.0.3 and downloaded from repo.jellyfin.org andriod jellyfin 1.0.2 cannot connect to my jellyfin server. But it is normal to use web access. Access to ios devices is also normal. Do you have any relevant clues to help me solve it? Thank you.

**Comment by jakclynn** [comment] 2020-08-12 09:48
There doesn't seem to be a permission setting to request a network usage in miui's app rights management.

**Comment by ThaChillera** [comment] 2020-08-12 12:26
Might be related to #327 ?

**Comment by thornbill** [comment] 2020-08-12 14:22
Sounds like this could be a duplicate of #380

**Closed by thornbill** 2020-08-12 14:22 UTC
