### ISSUE TITLE
android client can't connect using same link as web version

### ISSUE THREAD

**Issue by rpelissi** [jellyfin/jellyfin-android#192] opened 2019-09-13 02:16 UTC
Hi,
I am using jellyfin Web 10.3.7 inside a docker/rancher setup. I am access it using a load balancer (http) on port 80 and everything is working fine. 
But when I try to connect to the same url/host/port, the jellyfin android app (5 Sept 2009 0.9.2) the app can't connect/find the server.

Let me know if you need more details.
Thanks! Such a great media system :)

**Comment by anthonylavado** [comment] 2019-09-15 22:12
@rpelissi Hi there! There's a small change to the URL input on this version. You have to specify the port inline.

Some examples:
`example.com:8096`
`192.168.0.100:8096`
`http://example.com:8096`
`https://example.com:8096`

Of course, if 8096 isn't the port you're using, change it to the correct one. Let me know if this helps!

**Comment by anthonylavado** [comment] 2019-09-16 05:40
We've updated the example in at least the English strings to show this change.

**Comment by Pigney** [comment] 2019-09-20 02:32
I have this exact same problem, using the ip and port inline.
Something isn't right.

**Comment by rpelissi** [comment] 2019-09-26 15:51
Hi,
For me it was an issue with my rancher/kubernetes system. Now everything is working :) Thanks again!

**Comment by anthonylavado** [comment] 2019-09-27 03:17
Whoops. Wrong button. @Pigney Can you share any more details? Does it not find the server at all? Are you using a reverse proxy? SSL?

**Comment by ccrabit** [comment] 2019-10-03 13:05
I had the same things with you. what happened ?

**Comment by JustAMan** [comment] 2019-10-08 10:46
@ccrabit 
According to the logs of original poster, most likely external server for fetching a public IP of the JF system failed or was firewalled.
As of Jellyfin 10.4.0, we no longer talk to external servers (as we no longer provide "WAN IP" information via API in Jellyfin).

**Comment by Derkades** [comment] 2019-11-10 12:33
It used to work, but now I am having this issue with
* Reverse proxy using the official configuration file `https://media.mydomain.com:443`
* The local server `192.168.1.111:8096`
* Port forwarded server `mydomain.com:8096`

All addresses above work in the browser

**Comment by mazzystr** [comment] 2019-11-11 16:56
I cannot connect to my server at all.  

I use Jellyfin 10.4.1, "BaseUrl: /jellyfin" and a haproxy for reverse proxy and ssl offload.  

I've tried the following...
host: https://192.168.0.10:8443/  port: 8443
host: https://192.168.0.10:8443/jellyfin  port: 8443

Desktop web browsers can connect to jellyfin and stream A-OK.  I have other mobile apps that connect to apps behind this haproxy A-OK.

**Comment by lewazo** [comment] 2019-11-11 21:03
> It used to work, but now I am having this issue with
> 
>     * Reverse proxy using the official configuration file `https://media.mydomain.com:443`
> 
>     * The local server `192.168.1.111:8096`
> 
>     * Port forwarded server `mydomain.com:8096`
> 
> 
> All addresses above work in the browser
> 
> EDIT: Fixed, apparently since [version 10.4.1](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1) you now have to add `/jellyfin` to the URL

Thanks, that fixed it for me!

**Comment by mazzystr** [comment] 2019-11-12 06:39
I just did some tinkering and apearrently the mobile app does not like ssl or my haproxy ssl offload settings.  I can do standard http with port redirect (8080->8096) and baseurl: /jellyfin and connect to my server A-OK.  As soon as I enable ssl the connection fails.  

I tried using the following settings...
```
frontend s_jellyfin
    bind *:443 ssl crt /usr/local/etc/haproxy/local.pem alpn h2,http/1.1
    use_backend jellyfin

backend jellyfin
    server jellyfin 172.30.1.9:8096 check inter 5
```

My cert is self signed for internal/use.  I plan on moving to a Let's Encrypt cert for internet based clients.

**Comment by JustAMan** [comment] 2019-11-12 10:21
There currently is no good way of enabling self-signed certificates in the app.
You can use a browser on your phone which can be set up to accept that certificate, or install your self CA into your phone trusted storage. Or better just move to Let's Encrypt :)

**Comment by dkanada** [comment] 2019-11-29 15:19
The original issue has been fixed so I'll close this. @mazzystr if you want to get more information about the self-signed certificate issues I think #63 is related.

**Closed by dkanada** 2019-11-29 15:19 UTC
Labels: bug

**Comment by MakiseKurisu** [comment] 2020-05-16 03:14
Sorry for bringing up this old issue. My jellyfin server also uses "BaseUrl: /jellyfin". When I open my server through ip:port in browser, it automatically redirects me to ip:port/jellyfin/. However when I tried to connect through Android client, I have to enter the whole "ip:port/jellyfin/". Is this intended behavior for Android client to not supporting URL redirection?

**Comment by anthonylavado** [comment] 2020-05-16 05:04
@MakiseKurisu This is the intended behaviour for now.

**Comment by spikerguy** [comment] 2020-06-11 22:51
I have a similar issue.
I can connect to my static ip with my custom port with a browser over external network but cannot connect the same ip:port using android app. I have used the same phone and same network to connect to jellyfin server in the browser and it work fine. 
I am using jellyfin in docker and latest android app.
I have only forwarded http port that is 9090 for me Do I have to forward 1900 also ? As my router doesn't allow me to forward that port and I cannot change it in jellyfin.

Please advice.
Thanks. BTW I am loving jellyfin while testing it :D
