### ISSUE TITLE
LiveTV Playback not ending after closing app

### ISSUE THREAD

**Issue by BillApple** [jellyfin/jellyfin-android#1219] opened 2023-11-23 15:50 UTC
### Describe the bug

Media Source: Over-the-Air (OTA) TV
Using HDHomerun and xteve

My issue:
If I end Playback in the jellyfin app, the jellyfin server/HDHomerun does not seem to realize that Playback has ended. As a result, every time i exit the app, one of my tuners gets locked to a channel on the HDHomerun.

Each time I run out of available tuners, and I am forced to manually reset jellyfin and my hdhomerun.

I tried troubleshooting this by bypassing xteve and directly connecting the HDHomerun to jellyfin, but the issue remained the same.

### Application version

2.6.0-beta.2

### Where did you install the app from?

Google Play

### Device information

Pixel 7 Pro

### Android version

Android

### Jellyfin server version

10.8.12

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment] 2024-02-13 20:19
Duplicate of #1279 (merging into later issue as it has more details).

**Closed** 2024-02-13 20:20 UTC
Labels: bug, duplicate
