### ISSUE TITLE
Auto discovery feature breaks in release flavour

### ISSUE THREAD

**Issue by CarlosOlivo** [jellyfin/jellyfin-android#147] opened 2020-09-28 22:14 UTC
**Describe the bug**
Maybe more proguard rules are needed? The debug flavour works fine

**To Reproduce**

1. Clear app data
1. Install jellyfin-android-v2.0.0-rc.6-release.apk or build debug flavor from master with minify & proguard enabled
2. Tap "CHOOSE SERVER" button

**Expected behavior**

1. Clear app data
1. Install jellyfin-android-v2.0.0-rc.6-debug.apk build debug flavor from master with minify & proguard disabled
2. Tap "CHOOSE SERVER" button
4. All OK

**Logs**
I can't find any lines that can help due to the obfuscation itself, if the obfuscation is totally disabled it works correctly again.

```
2020-09-28 16:55:58.387 2325-8572/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.jellyfin.mobile.debug/org.jellyfin.mobile.MainActivity} from uid 10166
2020-09-28 16:55:58.399 2325-2360/? E/system_server: Invalid ID 0x00000000.
2020-09-28 16:55:59.528 15262-15262/? W/in.mobile.debu: Core platform API violation: Ljava/lang/Class;->dexCache:Ljava/lang/Object; from Lcom/elderdrivers/riru/edxp/core/yahfa/HookMethodResolver; using JNI
2020-09-28 16:55:59.528 15262-15262/? W/in.mobile.debu: Core platform API violation: Ljava/lang/DexCache;->resolvedMethods:J from Lcom/elderdrivers/riru/edxp/core/yahfa/HookMethodResolver; using JNI
2020-09-28 16:55:59.528 15262-15262/? W/in.mobile.debu: Core platform API violation: Ljava/lang/Thread;->nativePeer:J from Lde/robv/android/xposed/XposedHelpers; using reflection
2020-09-28 16:55:59.683 15262-15262/? W/in.mobile.debu: Core platform API violation: Ljava/lang/Class;->status:I from Lde/robv/android/xposed/XposedHelpers; using reflection
2020-09-28 16:55:59.684 9919-9919/? W/adbd: timeout expired while flushing socket, closing
2020-09-28 16:55:59.768 7969-19167/? W/NetworkScheduler: Error inserting flex_time=6000 job_id=-1 period=14000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203615000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1601330159766 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]
2020-09-28 16:55:59.806 7320-7389/? W/System: A resource failed to call release. 
2020-09-28 16:55:59.806 7320-7389/? W/System: A resource failed to call release. 
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/b/m/a/b;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.c is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.d is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.e is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.f is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/e/i$c;.g is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/g/j;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/g/j;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/p/z$d;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/p/z$d;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.c is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.d is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.f is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.h is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.846 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/u/e0;.i is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.847 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lcom/google/android/exoplayer2/util/PriorityTaskManager;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.847 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lcom/google/android/exoplayer2/util/PriorityTaskManager;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.848 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/c/c/u/z;.e is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.849 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/c/h/a/a;.P1 is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.849 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/c/h/b/a;.P1 is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.849 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/c/h/d/b;.P1 is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.849 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/g0/d;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.A is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.C is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.D is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.I is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.V is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.Z is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.m is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.850 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/z/a;.y is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.856 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/h/g/l/e;.c is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.860 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/c/d/k/a$a;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.c is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.d is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.e is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.f is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.g is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.h is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.861 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Le/b/a/d/n/b;.i is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.866 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Landroidx/webkit/WebViewClientCompat;.a is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.866 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/q/n/o$b;.F is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.866 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/q/n/o$b;.K is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.866 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/q/n/o$b;.P is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.866 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/q/n/o$b;.Q is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.869 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/l/a/c;.f1 is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
2020-09-28 16:55:59.869 15262-15262/org.jellyfin.mobile.debug W/in.mobile.debu: Method Lc/q/n/o$c;.U is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/org.jellyfin.mobile.debug-mtUt_PbkxIKVyoMAOKlakw==/base.apk
```

**Screenshots**
v2.0.0-rc.6, release flavor
![image](https://user-images.githubusercontent.com/25919231/94490946-de450500-01ac-11eb-99b7-7b1c8c7a78c6.png)

v2.0.0-rc.6, debug flavor
![image](https://user-images.githubusercontent.com/25919231/94490966-e9983080-01ac-11eb-852c-44012d9bdaec.png)

Master branch, debug flavor with minify & proguard enabled
![image](https://user-images.githubusercontent.com/25919231/94490991-f1f06b80-01ac-11eb-8148-473141949a5d.png)

Master branch, debug flavor with minify & proguard disabled
![image](https://user-images.githubusercontent.com/25919231/94491005-f61c8900-01ac-11eb-970c-82de27a3baf4.png)

**System (please complete the following information):**
 - App version: [e.g. 2.0.0-rc.2] v2.0.0-rc.6
 - Android version: [e.g. Android 10] Android 10
 - Device manufacturer and model: [e.g. Google Pixel 4, Samsung Galaxy S20] Xiaomi Pocophone F1
 - Jellyfin server version: [e.g. 10.5.4] 10.6.4
 - The type of video player implementation used: [web player or integrated player (ExoPlayer)] N/A

**Additional context**
This maybe should go in jellyfin/jellyfin-apiclient-java but I think it is not necessary to report every unanswered request as an error
```
2020-09-28 17:07:20.629 18707-25938/org.jellyfin.mobile.debug E/TimberLogger: Discovery: Unable to receive message
    java.net.SocketTimeoutException: Poll timed out
        at libcore.io.IoBridge.poll(IoBridge.java:682)
        at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:150)
        at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:141)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:164)
        at java.net.DatagramSocket.receive(DatagramSocket.java:847)
        at org.jellyfin.apiclient.discovery.ServerDiscovery.receive(ServerDiscovery.kt:53)
        at org.jellyfin.apiclient.discovery.ServerDiscovery.access$receive(ServerDiscovery.kt:19)
        at org.jellyfin.apiclient.discovery.ServerDiscovery$discover$1.invokeSuspend(ServerDiscovery.kt:103)
        at org.jellyfin.apiclient.discovery.ServerDiscovery$discover$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:60)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:161)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:128)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Maxr1998** [comment] 2020-09-28 23:02
Oh no, not again 😢 
Thanks for the report, I'll look into it.
*Good that we did an RC first..*

**Comment by nielsvanvelzen** [comment] 2020-09-29 06:35
I think this is caused by the data class for the server discovery results not living in the .model package. It will definitely be fixed in the next apiclient version (due too the switch the kotlinx.serialization and the class being moved to the .model package).

I think I'll need to release a patch version for now though.

**Closed** 2020-09-29 11:50 UTC
Labels: bug
