### ISSUE TITLE
Local connection switching

### ISSUE THREAD

**Issue by sum01** [jellyfin/jellyfin-android#319] opened 2021-03-11 18:28 UTC
**Describe the feature you'd like**

When one (or more) specified WiFi SSID's are connected, the connection switches to using a specified LAN address instead of a domain/WAN address.

Example: You give two addresses (if switching is enabled), one for your domain to access through WAN, and another local IP to use when you connect to your home WiFi.

**Additional context**

Basically just what the nzb360 app does, which allows you to specify different address for WAN & LAN, and it swaps based on if you connect to any SSID in a given list.

This is useful (at least to me) since WAN upload is limited, but LAN is capable of much higher speeds. I have to force transcoding on any external IPs but my LAN is basically unlimited.

Here's an example from nzb360

![nzb360](https://user-images.githubusercontent.com/19376155/110834947-2b54f900-826c-11eb-96e7-d326dee4325a.jpg)

**Comment by nielsvanvelzen** [comment] 2021-03-11 19:32
Duplicate of #291

**Closed by nielsvanvelzen** 2021-03-11 19:32 UTC
Labels: enhancement

**Comment by sum01** [comment] 2021-03-11 19:42
Is that really the same thing? What I'm proposing switches to the LAN IP automatically if wifi connects to a specific SSID.

That issue just says to offer a list if multiple are available.

I guess it could more or less be the same proposal though.

**Comment by nielsvanvelzen** [comment] 2021-03-11 21:22
It's a slightly different method of achieving the same goal; allowing multiple servers. I'd say your suggestion to automatically select a server based on the network you're connected to is an addition to the linked issue.
