### ISSUE TITLE
Jellyfin loses control of Chromecast while it is playing

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin-android#464] opened 2021-07-12 01:14 UTC
**Describe the bug**

After media is playing to Chromecast for a while, the remote control becomes inoperative. It's almost as if it detaches from the Chromecast. Disconnecting, then clicking the Cast icon and selecting the same device does nothing until the app is stopped and restarted.

**To Reproduce**

1. Start playing media via Chromecast
2. Wait a while? Switch apps, I dunno exactly. Maybe even close Jellyfin app and reopen it.
3. Attempt to control the media with the Chromecast remote in Jellyfin.

**Expected behavior**

Jellyfin should never lose control of the media it is casting.

**Logs**

I do not have adb or root to capture logs, but, let me know if you really need the logs and I'll see what I can do when I have time.

**Screenshots**

![Screenshot_20210710-230944](https://user-images.githubusercontent.com/1128849/125210933-f5e30b00-e25f-11eb-974d-37d39f89a26a.jpg)

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: 10
 - Device manufacturer and model: Google Pixel 4
 - Jellyfin server version: 10.7.6
 - The type of video player implementation used: Web player, I guess?

**Additional context**

None that I can think of.

**Comment by Maxr1998** [comment] 2021-07-12 12:12
Duplicate of #459.

**Closed** 2021-07-12 12:12 UTC
Labels: bug, duplicate

**Comment by mholt** [comment] 2021-07-12 14:54
@Maxr1998 I saw that one. This is not a duplicate. For me, the controls do not disappear immediately. It takes some amount of time.

**Comment by Maxr1998** [comment] 2021-07-12 15:39
I'm pretty sure it's the same issue though. Something in jellyfin-web must have changed an broke the casting code on the Android side.

**Comment by mholt** [comment] 2021-07-12 16:07
Ok, so should this be moved into jellyfin-web then? (Sorry, not too familiar with which component is relevant here.)

**Comment by Maxr1998** [comment] 2021-07-13 08:51
I'd keep it here for now, since it's more a combination of web changes and the custom Android casting code.

**Comment by EFCAugure** [comment] 2021-08-03 19:27
also related to [https://github.com/jellyfin/jellyfin-android/issues/315](url)  ?
