### ISSUE TITLE
Play/pause button and other controls go missing

### ISSUE THREAD

**Issue by linucksrox** [jellyfin/jellyfin-android#219] opened 2019-11-02 00:16 UTC
When I'm playing a video:

- Tap the screen to show playback controls
- tap the pause button (and I notice it remains highlighted like it's selected)
- tap the screen to hide playback controls
- tap the screen again to show playback controls, except the play/pause button is now missing.

I can reproduce this with the other controls, leaving only the settings button and I have to use the back arrow to stop playback to get it all working again.

Android 10, Pixel 3a latest jellyfin server 10.4.0 and latest jellyfin Android version from Google play store 0.9.4

**Comment by anthonylavado** [comment] 2019-11-03 07:36
Duplicate of jellyfin/jellyfin-web#530, so closing. If I'm wrong and your case is different feel free to comment here.

**Closed by anthonylavado** 2019-11-03 07:36 UTC
