### ISSUE TITLE
"Web page not available" shown if server is off

### ISSUE THREAD

**Issue by yashx** [jellyfin/jellyfin-android#131] opened 2020-09-16 15:33 UTC
**Describe the bug**

If I open the app when the server is off. I get a screen showing "Web page not available". I was able to fix it by starting the server and then opening the app or by clearing app data. 

**To Reproduce**

1. Start Jellyfin server
2. Connect using the Android App
3. Close the app
4. Stop the server
5. Open the app

**Expected behavior**

Show "connect to server" screen and give a reason if it can't connect 

**Screenshots**

https://imgur.com/a/Nsl8Zbb

**System:**
 - App version: 2.0.0-rc.5
 - Android version: Android 10
 - Device manufacturer and model: Xiaomi Pocophone F1
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment] 2020-09-16 15:36
Duplicate of #44

**Closed by nielsvanvelzen** 2020-09-16 15:36 UTC
Labels: bug
